// Investigation-style phishing scenarios (defensive education only).
export type PhishingClue = {
  id: string;
  label: string;
  detail: string;
  whyItMatters: string;
};

export type PhishingScenario = {
  id: string;
  slug: string;
  title: string;
  category: string;
  difficulty: 1 | 2 | 3;
  senderName: string;
  senderAddress: string;
  realDomain: string;
  subject: string;
  body: string;
  linkText: string;
  linkDestination: string;
  hasAttachment?: string;
  isPhishing: boolean;
  clues: PhishingClue[];
  safeAction: string;
  safeActionWhy: string;
  riskyActions: string[];
  xpReward: number;
};

export const phishingScenarios: PhishingScenario[] = [
  {
    id: 'ph-bank-otp',
    slug: 'bank-otp-scam',
    title: 'Bank security alert',
    category: 'Bank phishing',
    difficulty: 1,
    senderName: 'Bank Security',
    senderAddress: 'security@bank-secure-alerts.com',
    realDomain: 'yourbank.com',
    subject: 'Unusual activity — verify within 24 hours',
    body: 'Dear Customer,\n\nWe detected unusual activity on your account. Verify your identity now or your account will be restricted.\n\nUse the link below to confirm your details.',
    linkText: 'Verify my account',
    linkDestination: 'http://bank-secure-alerts.com/verify?session=abc123',
    isPhishing: true,
    clues: [
      { id: 'domain', label: 'Sender domain mismatch', detail: 'Sender uses bank-secure-alerts.com, not yourbank.com.', whyItMatters: 'Real banks always email from their own domain. A lookalike domain is the strongest sign of phishing.' },
      { id: 'urgency', label: 'Urgency tactic', detail: '"within 24 hours or restricted".', whyItMatters: 'Urgency pushes you to act before thinking. Real banks give you time and other channels.' },
      { id: 'generic', label: 'Generic greeting', detail: '"Dear Customer" instead of your name.', whyItMatters: 'Your bank knows your name. Mass phishing cannot personalize every message.' },
      { id: 'link', label: 'Link destination mismatch', detail: 'Link goes to bank-secure-alerts.com over plain http, not yourbank.com over https.', whyItMatters: 'Hover before you click. The real destination reveals the impersonation.' },
    ],
    safeAction: 'Do not click. Open your bank app directly (or type yourbank.com yourself) and check for alerts there.',
    safeActionWhy: 'Verifying through a separate trusted channel breaks the attacker’s link between message and fake site.',
    riskyActions: ['Clicking the verify link', 'Replying with your account number', 'Forwarding your OTP code'],
    xpReward: 40,
  },
  {
    id: 'ph-uni-scholarship',
    slug: 'university-scholarship-fee',
    title: 'Scholarship award with a fee',
    category: 'Scholarship phishing',
    difficulty: 1,
    senderName: 'Scholarship Board',
    senderAddress: 'awards@scholarship-foundation-apply.net',
    realDomain: 'youruniversity.edu',
    subject: 'Congratulations! You won a $5,000 scholarship',
    body: 'Dear Student,\n\nYou have been selected for a $5,000 merit scholarship. To release the funds, confirm your student ID and pay a $50 processing fee within 48 hours.',
    linkText: 'Claim scholarship',
    linkDestination: 'https://scholarship-foundation-apply.net/claim?id=9981',
    isPhishing: true,
    clues: [
      { id: 'fee', label: 'Advance fee request', detail: 'Real scholarships never ask you to pay to receive money.', whyItMatters: 'Any “pay to receive” request is an advance-fee scam pattern.' },
      { id: 'domain', label: 'Unofficial sender domain', detail: 'scholarship-foundation-apply.net is not youruniversity.edu.', whyItMatters: 'Schools announce awards through official portals and .edu addresses.' },
      { id: 'unsolicited', label: 'You never applied', detail: 'You cannot win a program you never entered.', whyItMatters: 'Unsolicited winnings are always fake.' },
    ],
    safeAction: 'Check your university portal directly. Never pay a fee to receive a scholarship.',
    safeActionWhy: 'Official portals are the source of truth; email is only a notification.',
    riskyActions: ['Paying the $50 fee', 'Sending your student ID and bank details'],
    xpReward: 40,
  },
  {
    id: 'ph-delivery-fee',
    slug: 'delivery-redelivery-fee',
    title: 'Package redelivery fee',
    category: 'Delivery phishing',
    difficulty: 1,
    senderName: 'Express Delivery',
    senderAddress: 'tracking@express-delivery-track.info',
    realDomain: 'expressdelivery.com',
    subject: 'Delivery failed — pay $1.99 redelivery fee',
    body: 'Hi,\n\nWe could not deliver your package. Pay a small redelivery fee to schedule a new delivery time.',
    linkText: 'Schedule redelivery',
    linkDestination: 'http://express-delivery-track.info/pay?tracking=94001112',
    isPhishing: true,
    clues: [
      { id: 'fee', label: 'Unexpected fee via link', detail: 'Legitimate carriers do not collect redelivery fees through random email links.', whyItMatters: 'Payment links in unexpected delivery messages are a top smishing pattern.' },
      { id: 'domain', label: 'Lookalike tracking domain', detail: 'express-delivery-track.info vs expressdelivery.com.', whyItMatters: 'Typosquatting and extra words are classic impersonation tricks.' },
      { id: 'context', label: 'No order context', detail: 'No tracking number you recognize, no order name.', whyItMatters: 'Real notifications reference something you actually ordered.' },
    ],
    safeAction: 'Paste the tracking number into the official carrier site yourself. Delete the message.',
    safeActionWhy: 'Manual navigation avoids the malicious link entirely.',
    riskyActions: ['Paying the fee', 'Entering card details on the linked page'],
    xpReward: 40,
  },
  {
    id: 'ph-ms-login',
    slug: 'fake-microsoft-login',
    title: 'Microsoft password expiry',
    category: 'Fake login',
    difficulty: 2,
    senderName: 'Microsoft Account',
    senderAddress: 'account-security@micorosoft-verify.com',
    realDomain: 'microsoft.com',
    subject: 'Your password expires today',
    body: 'Hi,\n\nYour Microsoft password expires today. Sign in below to keep your account active.\n\nFailure to act may result in loss of access to Outlook and OneDrive.',
    linkText: 'Keep my account active',
    linkDestination: 'https://micorosoft-verify.com/signin?user=you',
    hasAttachment: undefined,
    isPhishing: true,
    clues: [
      { id: 'typo', label: 'Typosquatted domain', detail: 'micorosoft (with an o) instead of microsoft.', whyItMatters: 'One-letter differences are designed to fool quick glances.' },
      { id: 'threat', label: 'Threat of loss', detail: '“Loss of access” creates fear.', whyItMatters: 'Fear short-circuits careful checking. Pause and verify elsewhere.' },
      { id: 'link', label: 'Credential harvesting link', detail: 'Link leads to a non-Microsoft domain asking for a password.', whyItMatters: 'Microsoft never asks you to sign in from a third-party domain.' },
    ],
    safeAction: 'Go to account.microsoft.com yourself. Check security info there.',
    safeActionWhy: 'Typing the address yourself guarantees you reach the real site.',
    riskyActions: ['Signing in on the linked page', 'Reusing that password elsewhere afterwards'],
    xpReward: 50,
  },
  {
    id: 'ph-job-offer',
    slug: 'fake-job-recruiter',
    title: 'Too-good job offer',
    category: 'Job phishing',
    difficulty: 2,
    senderName: 'Global Recruiting',
    senderAddress: 'hiring@global-careers-offer.com',
    realDomain: 'known-company.com',
    subject: 'You are hired! Remote role — $4,500/month, no interview',
    body: 'Hello,\n\nWe reviewed your profile and want to hire you immediately as a remote payment assistant. No interview needed. You will receive funds and forward them, keeping 10%.\n\nReply with your full name, address, bank name, and a copy of your ID to start.',
    linkText: 'Accept offer document',
    linkDestination: 'https://global-careers-offer.com/offer-letter.doc',
    hasAttachment: 'offer-letter.doc (unexpected)',
    isPhishing: true,
    clues: [
      { id: 'no-interview', label: 'No real hiring process', detail: 'No legitimate job hires with zero interview.', whyItMatters: 'Skipping verification is how money-mule scams recruit.' },
      { id: 'mule', label: 'Forward-money task', detail: 'Receiving and forwarding funds is money laundering.', whyItMatters: 'You could become criminally liable even as a victim.' },
      { id: 'id-request', label: 'ID + bank details up front', detail: 'Asking for ID copy and bank info by email.', whyItMatters: 'That combination enables identity theft.' },
      { id: 'domain', label: 'Generic recruiting domain', detail: 'global-careers-offer.com, no verifiable company presence.', whyItMatters: 'Real offers come from company domains and verifiable postings.' },
    ],
    safeAction: 'Stop. Do not reply or send documents. Verify the company on its official site and report the message.',
    safeActionWhy: 'Money-mule and fake-job scams escalate fast once you engage.',
    riskyActions: ['Sending ID documents', 'Accepting and forwarding payments'],
    xpReward: 60,
  },
  {
    id: 'ph-legit-bank',
    slug: 'legit-bank-alert',
    title: 'Real bank security notice',
    category: 'Legitimate',
    difficulty: 2,
    senderName: 'YourBank',
    senderAddress: 'alerts@yourbank.com',
    realDomain: 'yourbank.com',
    subject: 'New sign-in to your account',
    body: 'Hi Ada,\n\nWe noticed a new sign-in to your account from Chrome on Windows. If this was you, you can ignore this message. If not, open your bank app and change your password, then contact us at the number on your card.',
    linkText: 'No links — open your app',
    linkDestination: '(no link in message)',
    isPhishing: false,
    clues: [
      { id: 'domain', label: 'Correct domain', detail: 'alerts@yourbank.com matches the real domain.', whyItMatters: 'Matching domain is the first positive signal.' },
      { id: 'personal', label: 'Personalized + non-urgent', detail: 'Uses your name and says “you can ignore if this was you”.', whyItMatters: 'Legitimate alerts inform without pressuring.' },
      { id: 'no-link', label: 'No credential link', detail: 'Tells you to use your app, not click.', whyItMatters: 'Real companies avoid asking for passwords by email.' },
    ],
    safeAction: 'If you do not recognize the sign-in, open your app directly and secure the account.',
    safeActionWhy: 'Direct navigation keeps you on the real service.',
    riskyActions: ['Searching for a “bank login” link and clicking ads', 'Ignoring a sign-in you do not recognize'],
    xpReward: 40,
  },
  {
    id: 'ph-uni-login',
    slug: 'university-password-expiry',
    title: 'University password expiry',
    category: 'University phishing',
    difficulty: 2,
    senderName: 'University IT Services',
    senderAddress: 'it-helpdesk@univ-portal-support.com',
    realDomain: 'youruniversity.edu',
    subject: 'Your student password expires in 24 hours',
    body: 'Dear Student,\n\nYour university password expires tomorrow. Failure to renew now will lock you out of email, classes, and grades.\n\nClick below to renew immediately.',
    linkText: 'Renew password now',
    linkDestination: 'http://univ-portal-support.com/renew?u=student',
    isPhishing: true,
    clues: [
      { id: 'domain', label: 'Non-.edu sender', detail: 'univ-portal-support.com instead of youruniversity.edu.', whyItMatters: 'Schools always use their own .edu domain for account notices.' },
      { id: 'urgency', label: 'Lockout threat', detail: '"Locked out of grades" is designed to panic students.', whyItMatters: 'Fear makes you skip the domain check. Pause first.' },
      { id: 'generic', label: 'Generic greeting', detail: '"Dear Student" — the school knows your name.', whyItMatters: 'Mass phishing cannot personalize.' },
      { id: 'link', label: 'Password link over http', detail: 'Renewal link goes to a non-university domain without https.', whyItMatters: 'Never type a password from an emailed link.' },
    ],
    safeAction: 'Open your university portal by typing its address (or via the official app) and check notifications there.',
    safeActionWhy: 'The portal is the source of truth for your account status.',
    riskyActions: ['Renewing via the emailed link', 'Replying with your current password'],
    xpReward: 50,
  },
  {
    id: 'ph-social-reset',
    slug: 'social-media-password-reset',
    title: 'Social media reset you never asked for',
    category: 'Social media phishing',
    difficulty: 2,
    senderName: 'Instagram Security',
    senderAddress: 'security@instagram-verify-support.net',
    realDomain: 'instagram.com',
    subject: 'Password reset requested — confirm within 1 hour',
    body: 'Hi,\n\nSomeone requested a password reset for your account. If this was not you, your account may be compromised. Confirm your identity now to keep your account safe.',
    linkText: 'Confirm my identity',
    linkDestination: 'https://instagram-verify-support.net/reset?token=zzz',
    isPhishing: true,
    clues: [
      { id: 'domain', label: 'Lookalike support domain', detail: 'instagram-verify-support.net is not instagram.com.', whyItMatters: 'Platforms send security mail from their own domain only.' },
      { id: 'reverse', label: 'Reversed logic', detail: 'A reset YOU did not request means you should NOT click — go to the app instead.', whyItMatters: 'Attackers trigger fake resets, then harvest the credentials you "confirm".' },
      { id: 'urgency', label: 'One-hour deadline', detail: 'Countdowns stop you verifying.', whyItMatters: 'Real security mail lets you act in-app at your pace.' },
    ],
    safeAction: 'Ignore the link. Open the Instagram app yourself and check login activity; enable MFA.',
    safeActionWhy: 'In-app verification cannot be faked by an emailed link.',
    riskyActions: ['Confirming identity on the linked page', 'Sending the reset code to "support"'],
    xpReward: 50,
  },
  {
    id: 'ph-pw-reset',
    slug: 'generic-password-reset-trap',
    title: 'Password reset with attachment',
    category: 'Password reset phishing',
    difficulty: 3,
    senderName: 'Account Security',
    senderAddress: 'no-reply@account-protection-center.org',
    realDomain: '(varies — check the service you use)',
    subject: 'Reset your password — see attached instructions',
    body: 'Hello,\n\nA password reset was requested. Open the attached file for step-by-step instructions and complete the reset within 24 hours.\n\nIf you did not request this, open the attachment to cancel.',
    linkText: '(no link)',
    linkDestination: '(no link in message)',
    hasAttachment: 'Password-Reset-Instructions.html (unexpected)',
    isPhishing: true,
    clues: [
      { id: 'attach', label: 'Unexpected attachment', detail: 'Real reset flows use links to the official site, never HTML attachments.', whyItMatters: 'Attached HTML files open fake login pages that steal passwords.' },
      { id: 'sender', label: 'Vague sender', detail: '"Account Security" with a generic .org domain names no real service.', whyItMatters: 'Legitimate resets always name the service and come from its domain.' },
      { id: 'trap', label: '"Open to cancel" trap', detail: 'Both acting AND "cancelling" require opening the file.', whyItMatters: 'Either choice runs the attacker’s file. The safe move is neither.' },
    ],
    safeAction: 'Do not open the attachment. Delete the message; if worried, visit the service’s site directly.',
    safeActionWhy: 'Attachments can only harm you if opened. Direct navigation avoids the trap entirely.',
    riskyActions: ['Opening the HTML attachment', 'Typing your password into the opened file'],
    xpReward: 60,
  },
  {
    id: 'ph-gov-payment',
    slug: 'fake-government-payment',
    title: 'Government refund / fine notice',
    category: 'Fake government message',
    difficulty: 2,
    senderName: 'Tax Authority',
    senderAddress: 'refunds@tax-authority-online.com',
    realDomain: '(your country’s official .gov domain)',
    subject: 'You are owed a $280 tax refund — claim in 48 hours',
    body: 'Dear Citizen,\n\nOur records show you overpaid tax. Provide your bank details via the link below to receive your $280 refund before it expires. A small verification charge may apply.',
    linkText: 'Claim my refund',
    linkDestination: 'http://tax-authority-online.com/refund?case=4412',
    isPhishing: true,
    clues: [
      { id: 'domain', label: 'Non-government domain', detail: 'tax-authority-online.com — real agencies use official .gov domains.', whyItMatters: 'Government bodies do not process refunds from .com lookalikes.' },
      { id: 'bank', label: 'Bank details by link', detail: 'No agency collects bank logins through an emailed link.', whyItMatters: 'That combination is credential + financial theft.' },
      { id: 'expiry', label: 'Expiring refund', detail: 'Real refunds do not vanish in 48 hours.', whyItMatters: 'Expiry pressure is the tell.' },
    ],
    safeAction: 'Go to the official government site yourself (type it) or call a public helpline. Never enter bank details from a message link.',
    safeActionWhy: 'Official channels are the only safe path for tax and fines.',
    riskyActions: ['Claiming via the link', 'Paying the "verification charge"'],
    xpReward: 50,
  },
  {
    id: 'ph-bec-invoice',
    slug: 'boss-requests-urgent-payment',
    title: 'Urgent message from "the boss"',
    category: 'Business email phishing',
    difficulty: 3,
    senderName: 'Michael Torres (CEO)',
    senderAddress: 'm.torres@company-payments.com',
    realDomain: 'company.com',
    subject: 'Urgent: process invoice today',
    body: 'Hi,\n\nI am in meetings all day and unreachable by phone. Please process the attached invoice ($4,800) today and confirm once done. Keep this between us for now.\n\nThanks,\nMichael',
    linkText: '(no link)',
    linkDestination: '(no link in message)',
    hasAttachment: 'Invoice-4481.pdf (unexpected)',
    isPhishing: true,
    clues: [
      { id: 'domain', label: 'Near-miss company domain', detail: 'company-payments.com vs the real company.com.', whyItMatters: 'BEC attacks spoof executives with lookalike domains.' },
      { id: 'secrecy', label: 'Secrecy request', detail: '"Keep this between us" blocks verification.', whyItMatters: 'Real executives do not forbid confirming payments.' },
      { id: 'channel', label: 'Unreachable by phone', detail: 'Insisting on email-only avoids voice verification.', whyItMatters: 'The defense is a second channel: call the known number.' },
    ],
    safeAction: 'Stop. Verify through a different channel (call the boss on a known number / ask finance) before moving any money.',
    safeActionWhy: 'Out-of-band verification defeats executive impersonation.',
    riskyActions: ['Paying the invoice quickly to impress', 'Replying with payment confirmation details'],
    xpReward: 60,
  },
  {
    id: 'ph-support-chat',
    slug: 'fake-customer-support-dm',
    title: '“Support” slides into your DMs',
    category: 'Fake customer support',
    difficulty: 3,
    senderName: 'ShopHelp Support',
    senderAddress: '@shophelp-support-01 (social DM, 12 followers)',
    realDomain: '@shophelp (verified, 2M followers)',
    subject: 'Re: your complaint — refund available',
    body: 'Hi! We saw your complaint about your order. We can refund you right away. Just confirm your card number and the OTP we just sent so we can reverse the charge.',
    linkText: 'Refund form: bit.ly/shophelp-refund-2',
    linkDestination: 'https://bit.ly/shophelp-refund-2 (shortened, hides destination)',
    isPhishing: true,
    clues: [
      { id: 'account', label: 'Unverified support account', detail: '12 followers, recently created, username has extra words/numbers.', whyItMatters: 'Brands answer from verified accounts; scammers watch complaints and impersonate.' },
      { id: 'otp', label: 'Card + OTP request', detail: 'Refunds never need your card number AND an OTP in chat.', whyItMatters: 'That pair authorizes a charge AGAINST you, not a refund.' },
      { id: 'short', label: 'Shortened link', detail: 'bit.ly hides the real destination.', whyItMatters: 'Expand or avoid: go to the shop’s official site yourself.' },
    ],
    safeAction: 'Do not share card/OTP. Contact support via the shop’s official app/site and report the impersonator.',
    safeActionWhy: 'Official support channels plus reporting stop refund-scam impersonation.',
    riskyActions: ['Filling the refund form', 'Sharing the OTP "so they can reverse the charge"'],
    xpReward: 60,
  },
];
