// Traduction française des scénarios (2e partie : emploi, école, web, comptes).

import type { Scenario } from './scenarios';

export const scenariosFr2: Record<string, Scenario> = {
  'sc-hr-fee': {
    id: 'sc-hr-fee',
    slug: 'hr-processing-fee-job',
    title: 'Les RH demandent des frais de dossier',
    category: 'Job scams',
    channel: 'Telegram',
    sender: '« Sarah, RH » d’une entreprise de logistique (sur Telegram depuis un mois)',
    message: 'Félicitations ! Retenu pour le poste de Saisie de données : 150 000 FCFA/mois, à distance, sans entretien. Pour traiter votre dossier, envoyez 10 000 FCFA sur ce numéro MoMo aujourd’hui. Les places ferment ce soir.',
    thinkPrompt: 'Un salaire, sans entretien, et C’EST VOUS qui payez — ce soir. Dans quel sens circule l’argent dans une vraie embauche ?',
    choices: [
      {
        id: 'pay',
        text: 'Payer les 10 000 FCFA — le salaire en vaut la peine',
        verdict: 'unsafe',
        consequenceTitle: 'Payé. « Ensuite : 15 000 pour le certificat médical. »',
        consequence: 'Puis des frais d’uniforme, de formation… chaque étape assez petite pour sembler récupérable, jusqu’à 60 000 FCFA envolés et « Sarah » supprime son compte. Les vrais employeurs ne facturent jamais l’embauche.',
        feedback: 'Des frais-pour-être-embauché, c’est toute l’arnaque. L’argent circule employeur-vers-vous, jamais l’inverse.',
      },
      {
        id: 'verify',
        text: 'Demander un contrat et vérifier l’entreprise en indépendant',
        verdict: 'safe',
        consequenceTitle: 'Le vrai site de l’entreprise ne liste aucun poste — et alerte sur les arnaqueurs Telegram.',
        consequence: 'Vous trouvez leur page carrières officielle et un avertissement décrivant le même script. Vous signalez le compte et gardez vos 10 000.',
        feedback: 'Correct. Une vraie embauche survit à la vérification : site officiel, numéro public, contrat écrit.',
      },
      {
        id: 'id-first',
        text: 'Envoyer d’abord pièce d’identité et diplôme pour « bloquer la place »',
        verdict: 'risky',
        consequenceTitle: 'Place « bloquée ». La demande de frais arrive quand même.',
        consequence: 'Pire : ils détiennent votre photo d’identité et votre diplôme, utilisables pour usurpation et pour arnaquer d’autres en VOTRE nom.',
        feedback: 'Les documents d’abord, c’est aussi une perte. Pièce + diplôme = usurpation d’identité même sans paiement.',
      },
    ],
    redFlags: [
      { label: 'Embauche sans entretien', explanation: 'Personne ne paie 150 000/mois sans vous rencontrer.' },
      { label: 'Frais pour être embauché', explanation: 'Frais de dossier, médicaux, d’uniforme exigés des candidats = schéma d’arnaque.' },
      { label: 'Délai de ce soir', explanation: 'La fausse urgence bloque la vérification qui tuerait l’affaire.' },
      { label: 'RH sur Telegram uniquement', explanation: 'Compte récent, pas d’email d’entreprise, identité invérifiable.' },
    ],
    protect: ['Ne payez jamais pour être embauché.', 'Vérifiez les offres sur les sites officiels et numéros publics.', 'N’envoyez jamais de pièces d’identité par chat à des recruteurs non vérifiés.'],
    xpReward: 50,
  },
  'sc-exam-portal': {
    id: 'sc-exam-portal',
    slug: 'exam-results-portal',
    title: 'Consultez vos résultats d’examen ici',
    category: 'Student scams',
    channel: 'Groupe WhatsApp de classe',
    sender: 'Transféré de nombreuses fois : « Portail OFFICIEL des résultats — vérifiez avant fermeture ! »',
    message: 'Les résultats sont là ! Saisissez votre numéro de candidat ET votre mot de passe email scolaire pour voir vos notes avant la fermeture du portail : results-check-2026.com',
    thinkPrompt: 'L’excitation des résultats plus un champ mot de passe. Quand votre école a-t-elle eu besoin de votre mot de passe email pour afficher des notes ?',
    choices: [
      {
        id: 'enter',
        text: 'Saisir mon numéro de candidat et mon mot de passe email',
        verdict: 'unsafe',
        consequenceTitle: 'La page tourne… puis affiche une erreur. « Réessayez plus tard. »',
        consequence: 'Votre mot de passe email scolaire est récolté. Cette boîte mail réinitialise tout le reste : réseaux sociaux, codes MoMo, portails scolaires. Des jours plus tard, vos camarades reçoivent des arnaques « de votre part ».',
        feedback: 'Aucun portail de résultats ne demande votre mot de passe EMAIL. Le numéro de candidat suffit sur les vrais portails.',
      },
      {
        id: 'school-site',
        text: 'Aller moi-même sur le site de l’école / de l’office des examens',
        verdict: 'safe',
        consequenceTitle: 'Site officiel de l’office : « Résultats publiés vendredi. »',
        consequence: 'Les résultats ne sont même pas sortis — le portail transféré était pure fiction. Vous prévenez le groupe avec une capture (lien retiré) et l’admin supprime le message.',
        feedback: 'Correct. Les offices annoncent publiquement les dates. « Avant fermeture » est une fiction pour battre l’annonce.',
      },
      {
        id: 'friend-pass',
        text: 'Demander à un ami qui a « vérifié » son login à emprunter',
        verdict: 'risky',
        consequenceTitle: 'Votre amie partage son mot de passe pour « voir à quoi ça ressemble ».',
        consequence: 'Deux comptes compromis désormais, et vous avez normalisé le partage de mots de passe dans votre classe.',
        feedback: 'Les mots de passe empruntés doublent les dégâts. Vérifiez le portail, pas le login.',
      },
    ],
    redFlags: [
      { label: 'Mot de passe pour des notes', explanation: 'Les vrais portails demandent des numéros de candidat, pas des mots de passe email.' },
      { label: 'Frénésie de transferts', explanation: '« Transféré partout » + fermeture imminente = bousculade fabriquée.' },
      { label: 'Portail hors domaine', explanation: 'results-check-2026.com n’est pas le domaine de votre office d’examens.' },
    ],
    protect: ['N’utilisez que le site officiel de l’office, trouvé via recherche ou avis scolaire.', 'Ne saisissez jamais de mots de passe email sur des pages tierces.', 'Prévenez les groupes avec des captures, jamais en transférant le lien.'],
    xpReward: 50,
  },
  'sc-internship': {
    id: 'sc-internship',
    slug: 'paid-internship-abroad',
    title: 'Stage rémunéré à l’étranger',
    category: 'Job scams',
    channel: 'Message LinkedIn',
    sender: 'Recruteur au profil soigné (500+ relations, bannière de bureaux en banque d’images)',
    message: 'Votre profil est impressionnant ! Stage rémunéré de 3 mois à Dubaï : vols + indemnité 300 000 FCFA/mois. Réglez juste le traitement visa (45 000 FCFA) via notre agent agréé cette semaine.',
    thinkPrompt: 'Prestige, voyage, indemnité — et un paiement via « leur » agent. Que ferait différemment une vraie multinationale ?',
    choices: [
      {
        id: 'agent',
        text: 'Payer l’agent — opportunité Dubaï unique',
        verdict: 'unsafe',
        consequenceTitle: 'Reçu reçu. Puis : « frais d’ambassade », « frais d’assurance »…',
        consequence: 'Chaque frais en débloque un plus gros jusqu’à 150 000 FCFA envolés et le profil du recruteur qui disparaît. Les relations LinkedIn s’achètent ; les bureaux se téléchargent.',
        feedback: 'Les vrais employeurs utilisent les circuits visa officiels et ne routent jamais de paiements via des agents privés sous délai.',
      },
      {
        id: 'verify-co',
        text: 'Vérifier l’entreprise, le poste et l’agent en indépendant',
        verdict: 'safe',
        consequenceTitle: 'La vraie entreprise répond : « Nous n’avons aucun programme de ce type. »',
        consequence: 'Un email à leur contact public expose toute l’affaire. Le faux profil est signalé, et vos économies restent à vous.',
        feedback: 'Correct. Vérifiez les trois : entreprise (site officiel), poste (annonce officielle), agent (listes officielles).',
      },
      {
        id: 'passport',
        text: 'Envoyer la copie du passeport pour « réserver » le temps de réfléchir',
        verdict: 'risky',
        consequenceTitle: '« Réservé ! » La pression pour payer double désormais.',
        consequence: 'Vos données passeport circulent : usurpation, faux comptes à votre nom, et levier (« on a vos documents, payez ou else » — payez ou sinon).',
        feedback: 'Les copies de passeport sont de l’or pour les criminels. Jamais à des contacts non vérifiés.',
      },
    ],
    redFlags: [
      { label: 'Frais de visa/agent initiaux', explanation: 'Les programmes légitimes déduisent des indemnités ou passent par circuits officiels.' },
      { label: 'Offre prestigieuse non sollicitée', explanation: 'Les stages Dubaï tombés du ciel ciblent l’ambition, pas les qualifications.' },
      { label: 'Profil soigné mais creux', explanation: 'Relations et bannières sont bon marché ; un historique vérifiable ne l’est pas.' },
    ],
    protect: ['Vérifiez via le contact officiel — jamais les liens du recruteur.', 'Ne payez jamais d’agents pour des visas d’emploi sur des délais de chat.', 'Gardez passeports et pièces comme du liquide.'],
    xpReward: 50,
  },
  'sc-password-reuse': {
    id: 'sc-password-reuse',
    slug: 'one-password-everywhere',
    title: 'Un seul mot de passe partout',
    category: 'Account security',
    channel: 'Situation racontée (votre habitude)',
    sender: 'Vous, par efficacité',
    message: 'Vous utilisez « Lionel1999! » pour l’email, Facebook, MoMo, le portail scolaire et des sites de paris. Un jour, un petit forum rejoint en 2022 est piraté. Votre email + mot de passe circulent dans une liste fuitée sur Telegram.',
    thinkPrompt: 'Rien d’« important » n’a été piraté — juste un vieux forum. Pourquoi est-ce le scénario le plus dangereux ici ?',
    choices: [
      {
        id: 'nothing',
        text: 'Ignorer — ce forum ne signifie rien pour moi',
        verdict: 'unsafe',
        consequenceTitle: 'Des semaines plus tard : des emails de réinitialisation non demandés.',
        consequence: 'Bourrage d’identifiants : les attaquants rejouent votre paire fuitée contre email, Facebook et MoMo. Même mot de passe partout = une fuite ouvre toutes les portes.',
        feedback: 'Les fuites sont normales désormais. La question n’est jamais SI un mot de passe fuit — mais s’il ouvre autre chose.',
      },
      {
        id: 'change-all',
        text: 'Changer ce mot de passe partout et activer la MFA',
        verdict: 'safe',
        consequenceTitle: 'Nouveaux mots de passe uniques via gestionnaire + MFA sur l’email d’abord.',
        consequence: 'Le mot de passe fuité devient une clé morte. Les attaquants l’essaient sur cinquante sites et il n’ouvre rien. Dégâts totaux : zéro.',
        feedback: 'Correct. Les mots de passe uniques confinent les fuites ; la MFA sur l’email protège la clé maîtresse.',
      },
      {
        id: 'tweak',
        text: 'Ajouter « 123 » à la fin partout — suffisant',
        verdict: 'risky',
        consequenceTitle: '« Lionel1999!123 » partout. Les attaquants essaient les variantes automatiquement.',
        consequence: 'Les outils de bourrage mutent les mots de passe par défaut (chiffres, majuscules). Les retouches prévisibles tombent en minutes.',
        feedback: 'Les changements prévisibles se devinent par machine. Un mot de passe aléatoire unique par site est la vraie correction.',
      },
    ],
    redFlags: [
      { label: 'Identifiant réutilisé', explanation: 'Une fuite = tous les comptes, quand les mots de passe correspondent.' },
      { label: 'Pas de MFA', explanation: 'Sans second facteur, un mot de passe seul = accès total.' },
      { label: 'Vieux comptes oubliés', explanation: 'Les forums oubliés détiennent la clé que vous réutilisez.' },
    ],
    protect: ['Un gestionnaire : un mot de passe aléatoire unique par site.', 'MFA sur l’email d’abord, puis banque, MoMo, réseaux.', 'Après une fuite, changez ce mot de passe partout où il servait.'],
    xpReward: 40,
  },
  'sc-giveaway': {
    id: 'sc-giveaway',
    slug: 'influencer-giveaway-fee',
    title: 'Jeu-concours d’influenceur (payer la livraison)',
    category: 'Everyday scams',
    channel: 'Instagram',
    sender: 'Compte avec les photos d’un influenceur, 800 abonnés, « JEU-CONCOURS finit ce soir »',
    message: 'FÉLICITATIONS ! Vous avez gagné le jeu iPhone 15. Payez 5 000 FCFA de livraison via MoMo à ce numéro sous 2 heures pour recevoir votre lot.',
    thinkPrompt: 'Vous avez gagné sans participer, d’un compte à 800 abonnés, et le lot exige VOTRE paiement. Comptez les drapeaux.',
    choices: [
      {
        id: 'pay-ship',
        text: 'Payer les 5 000 FCFA de livraison — un iPhone vaut bien plus',
        verdict: 'unsafe',
        consequenceTitle: 'Payé. « Frais de douane ensuite : 12 000 FCFA. »',
        consequence: 'L’iPhone n’a jamais existé. L’échelle des frais continue jusqu’à votre arrêt — chaque marche « petite face à un iPhone ». Le compte vous bloque après le troisième paiement.',
        feedback: 'Les lots n’exigent jamais de paiements du gagnant. Frais de port/douane/vérification = arnaque aux frais avancés.',
      },
      {
        id: 'check-real',
        text: 'Vérifier le vrai compte certifié de l’influenceur',
        verdict: 'safe',
        consequenceTitle: 'Vrai compte (2 M d’abonnés) : aucun jeu, plus un avertissement anti-arnaque.',
        consequence: 'Le vrai influenceur a posté le mois dernier : « Des faux comptes font des jeux à mon nom. » Vous signalez l’usurpateur en deux gestes.',
        feedback: 'Correct. Abonnés, badge certifié et publications du vrai compte démasquent les usurpateurs.',
      },
      {
        id: 'tag-friend',
        text: 'Identifier des amis pour qu’ils gagnent aussi',
        verdict: 'risky',
        consequenceTitle: 'Trois amis « gagnent » dans l’heure.',
        consequence: 'Identifier recrute des victimes pour l’arnaqueur et dépense votre crédibilité. Vos amis perdent de l’argent parce que vous avez cautionné d’un tag.',
        feedback: 'N’amplifiez jamais des jeux non vérifiés. Les tags sont des cautions — vérifiez avant de les dépenser.',
      },
    ],
    redFlags: [
      { label: 'Gain sans participation', explanation: 'Les gains non sollicités sont toujours faux.' },
      { label: 'Frais pour recevoir', explanation: 'Les vrais lots déduisent ou sont gratuits — jamais de MoMo vers un numéro.' },
      { label: 'Compte usurpateur', explanation: 'Photos volées, peu d’abonnés, bio pressante.' },
      { label: 'Délai de 2 heures', explanation: 'La vitesse empêche la seule vérification qui tue l’arnaque.' },
    ],
    protect: ['Vérifiez les jeux sur le vrai compte certifié.', 'Ne payez jamais de frais pour recevoir des lots.', 'Signalez les usurpateurs au lieu d’identifier des amis.'],
    xpReward: 40,
  },
  'sc-qr-menu': {
    id: 'sc-qr-menu',
    slug: 'qr-menu-sticker',
    title: 'QR du menu avec un autocollant dessus',
    category: 'Safe browsing',
    channel: 'En personne (restaurant)',
    sender: 'QR de table avec un autocollant légèrement de travers sur l’original',
    message: 'Vous scannez. Votre navigateur ouvre « menu-restaurant-pay.com » qui demande de « se connecter avec Google pour voir le menu et payer depuis votre table ».',
    thinkPrompt: 'Un menu qui exige votre login Google. Quel rapport entre des prix et votre compte Google ?',
    choices: [
      {
        id: 'login-pay',
        text: 'Me connecter avec Google et payer — c’est pratique',
        verdict: 'unsafe',
        consequenceTitle: 'Connecté. Le menu fonctionne même !',
        consequence: 'L’autocollant était un recouvrement malveillant. Vos identifiants Google sont partis chez l’attaquant, qui possède désormais votre email — et via lui, les réinitialisations de tout. Le menu qui marche était le camouflage.',
        feedback: 'Les menus n’exigent jamais de login Google. Les autocollants sur QR sont une attaque connue — le recouvrement mène à la récolte d’identifiants.',
      },
      {
        id: 'ask-staff',
        text: 'Demander le vrai menu au personnel et vérifier l’URL',
        verdict: 'safe',
        consequenceTitle: 'Le personnel décolle l’autocollant : URL différente dessous.',
        consequence: 'Le vrai QR avait été remplacé le matin même. Le personnel retire tous les autocollants, vous commandez normalement, et l’attaquant ne reçoit rien de votre table.',
        feedback: 'Correct. Vérifiez les codes physiques comme les numériques : comparez avec le personnel, prévisualisez les URL.',
      },
      {
        id: 'photo-later',
        text: 'Photographier le QR et le scanner chez moi en Wi-Fi',
        verdict: 'risky',
        consequenceTitle: 'À la maison, même fausse page, même demande de login.',
        consequence: 'Le lieu n’a jamais compté — la destination était malveillante partout où vous l’ouvrez. Retarder ne désinfecte pas un mauvais lien.',
        feedback: 'Une destination malveillante l’est partout. Vérifiez la SOURCE, pas le réseau.',
      },
    ],
    redFlags: [
      { label: 'Code trafiqué', explanation: 'Autocollant de travers sur l’original = destination remplacée.' },
      { label: 'Login pour un menu', explanation: 'Aucun menu légitime ne demande votre compte Google.' },
      { label: 'Domaine sosie de paiement', explanation: 'menu-restaurant-pay.com n’est pas le site du restaurant.' },
    ],
    protect: ['Inspectez les QR (autocollants), confirmez avec le personnel.', 'Prévisualisez les URL avant d’ouvrir ; jamais de login depuis des QR aléatoires.', 'Tapez vous-même les adresses de paiement.'],
    xpReward: 40,
  },
  'sc-attachment-invoice': {
    id: 'sc-attachment-invoice',
    slug: 'invoice-attachment-email',
    title: 'Facture impayée en pièce jointe',
    category: 'Email threats',
    channel: 'Email',
    sender: '« Service Facturation » <billing@acme-corp-invoices.com>',
    message: 'Objet : Facture #INV-0451 EN RETARD — suspension sous 24 h. « Voir la facture jointe et payer pour éviter l’interruption. » Pièce jointe : Invoice-0451.html (47 Ko). Vous n’avez jamais entendu parler d’Acme Corp.',
    thinkPrompt: 'Une facture d’une société inconnue, avec pièce HTML et menace de 24 h. À QUOI sert la pièce jointe ?',
    choices: [
      {
        id: 'open',
        text: 'Ouvrir la pièce jointe pour voir ce que je devrais',
        verdict: 'unsafe',
        consequenceTitle: 'La « facture » s’ouvre dans votre navigateur et demande un login email « pour voir ».',
        consequence: 'Les pièces HTML affichent de fausses pages de login qui volent les mots de passe — et peuvent porter des malwares. La curiosité sur une dette inexistante vient de coûter de vrais mots de passe.',
        feedback: 'Les pièces jointes inattendues sont la charge, pas l’information. Expéditeur inconnu + dette inconnue = supprimer.',
      },
      {
        id: 'pay-call',
        text: 'Appeler le numéro dans la pièce jointe pour contester',
        verdict: 'risky',
        consequenceTitle: 'Un « agent facturation » répond et propose de « vérifier votre compte ».',
        consequence: 'Le numéro appartient aux arnaqueurs. L’appel de contestation devient une séance d’ingénierie sociale qui récolte vos données avec patience.',
        feedback: 'Les coordonnées dans un message frauduleux appartiennent à la fraude. Contestez via des numéros trouvés indépendamment.',
      },
      {
        id: 'delete-report',
        text: 'Supprimer et signaler comme hameçonnage — je ne dois rien à Acme',
        verdict: 'safe',
        consequenceTitle: 'Supprimé, signalé. Rien dû, rien ouvert.',
        consequence: 'Tout reposait sur la panique d’une fausse dette. Votre règle — pas de relation, pas de paiement, pas d’ouverture — règle ça en dix secondes.',
        feedback: 'Correct. Société inconnue + pièce inattendue + urgence = signaler et supprimer, sans échanger.',
      },
    ],
    redFlags: [
      { label: 'Facturier inconnu', explanation: 'On ne doit rien à une société jamais utilisée.' },
      { label: 'Pièce HTML', explanation: 'Les factures sont des PDF ; les .html ouvrent des pages de récolte.' },
      { label: 'Menace de suspension', explanation: 'Les menaces de 24 h fabriquent la panique qui ouvre les pièces.' },
    ],
    protect: ['N’ouvrez jamais de pièces inattendues — surtout .html, .doc à macros, .apk.', 'Vérifiez les dettes via les sociétés réellement utilisées, par canaux officiels.', 'Signalez l’hameçonnage au lieu de le contester avec l’expéditeur.'],
    xpReward: 50,
  },
  'sc-fake-profile': {
    id: 'sc-fake-profile',
    slug: 'fake-profile-friend-request',
    title: 'Nouvelle « vieille amie » sans historique',
    category: 'Social engineering',
    channel: 'Facebook / Instagram',
    sender: 'Demande d’amie de « Clarisse M. » — même nom et photos que votre ancienne camarade',
    message: 'Salut ! J’ai perdu l’accès à mon ancien compte, voici mon nouveau. Comment tu vas ?? Tu peux me rendre un petit service — j’ai besoin de ton aide pour voter pour mon cousin à un concours, envoie-moi juste le code que tu vas recevoir.',
    thinkPrompt: 'Même visage, nouveau compte, petit service avec un code. Que prouverait que c’est vraiment Clarisse ?',
    choices: [
      {
        id: 'code',
        text: 'Envoyer le code pour l’aider au concours',
        verdict: 'unsafe',
        consequenceTitle: 'Code envoyé. Déconnecté quelques minutes plus tard.',
        consequence: 'Le « code du concours » était VOTRE code de réinitialisation. Le profil était un clone — mêmes photos, zéro historique partagé. Votre compte spamme désormais le même concours à VOS amis.',
        feedback: 'Les profils clones récoltent photos et noms, puis arment la confiance. Les codes envoyés autorisent toujours quelque chose contre vous.',
      },
      {
        id: 'quiz-her',
        text: 'Poser une question que seule la vraie Clarisse connaît, sur un autre canal',
        verdict: 'safe',
        consequenceTitle: 'La vraie Clarisse répond : « Ce n’est pas moi — signale-le. »',
        consequence: 'Une question sur votre passé commun — posée via son numéro connu — fait s’effondrer l’usurpation. Le clone est signalé par vous deux.',
        feedback: 'Correct. Secrets partagés + canal indépendant battent l’usurpation. Les photos ne prouvent rien.',
      },
      {
        id: 'accept-chat',
        text: 'Accepter et discuter un moment pour « être sûr »',
        verdict: 'risky',
        consequenceTitle: 'Discussion amicale pendant trois jours. Puis la faveur arrive.',
        consequence: 'La patience est la méthode : d’abord le lien, ensuite la demande. Au moment du code, refuser semble impoli — c’était le plan.',
        feedback: 'Discuter ne vérifie pas l’identité ; ça construit la confiance que l’arnaque dépensera. Vérifiez d’abord, discutez après.',
      },
    ],
    redFlags: [
      { label: 'Marqueurs de clone', explanation: 'Mêmes photos, compte récent, peu d’amis, aucun historique ni tags partagés.' },
      { label: 'Faveur avec un code', explanation: 'Les votes de concours n’exigent jamais de codes DE VOTRE téléphone.' },
      { label: 'Recontact non sollicité', explanation: 'Contact sorti de nulle part + petite demande rapide = la mise en place.' },
    ],
    protect: ['Inspectez les nouveaux profils : âge, amis, historique, tags.', 'Vérifiez l’identité avec des souvenirs partagés sur un autre canal.', 'Signalez les clones ; prévenez les amis communs avec des mots, pas des transferts.'],
    xpReward: 50,
  },
  'sc-fake-certificate': {
    id: 'sc-fake-certificate',
    slug: 'fake-certificate-course',
    title: 'Payer un certificat, sauter la formation',
    category: 'Student scams',
    channel: 'Publicité Instagram + WhatsApp',
    sender: '« Global Skills Academy » — page pro, des certificats dans chaque post',
    message: 'Obtenez un Diplôme CERTIFIÉ en Marketing Digital en 48 heures — sans cours, sans examens. 25 000 FCFA seulement. Les employeurs vérifient nos certificats en ligne ! Payez via MoMo pour vous inscrire.',
    thinkPrompt: 'Un diplôme sans apprentissage, vérifié « en ligne », payable par MoMo. Qui reconnaît vraiment ce certificat ?',
    choices: [
      {
        id: 'pay-cert',
        text: 'Payer — un certificat booste vite mon CV',
        verdict: 'unsafe',
        consequenceTitle: 'Certificat PDF reçu. Il a l’air officiel.',
        consequence: 'Le « portail de vérification » est leur propre site qui affiche ce qu’ils tapent. Les vrais employeurs vérifient auprès d’organismes accrédités, pas de pages de diplômés. Vous avez payé 25 000 FCFA pour un PDF et un mensonge sur votre CV — qui peut coûter de vrais emplois.',
        feedback: 'Des diplômes sans apprentissage sont du papier, et du faux papier frôle la fraude. Les employeurs vérifient auprès des émetteurs, pas de leurs sites.',
      },
      {
        id: 'check-accredit',
        text: 'Vérifier l’accréditation auprès d’employeurs et organismes officiels',
        verdict: 'safe',
        consequenceTitle: 'Aucune accréditation nulle part. Aucun employeur ne les connaît.',
        consequence: 'Une recherche rapide plus une question à un professionnel révèle zéro reconnaissance. La « académie » n’existe que comme page et numéro MoMo. Votre argent reste à vous.',
        feedback: 'Correct. Vérifiez les diplômes comme les employeurs : accréditation indépendante, émetteurs reconnus, vrais anciens.',
      },
      {
        id: 'free-trial',
        text: 'Demander un échantillon gratuit pour « tester »',
        verdict: 'risky',
        consequenceTitle: 'Ils envoient un échantillon À VOTRE NOM. Impressionnant !',
        consequence: 'Les échantillons ne coûtent rien et ne prouvent rien — tout le monde sait mettre en page un PDF. Impressionnés, la plupart paient juste après l’échantillon.',
        feedback: 'Les échantillons prouvent le graphisme, pas l’accréditation. Jugez les émetteurs, pas les PDF.',
      },
    ],
    redFlags: [
      { label: 'Diplôme sans effort', explanation: 'Les vrais diplômes exigent apprentissage et évaluation. « 48 h, sans examens » est l’aveu.' },
      { label: 'Auto-vérification', explanation: '« Vérifiez sur notre site » signifie qu’ils contrôlent la réponse.' },
      { label: 'Inscription MoMo', explanation: 'Les institutions sérieuses utilisent admissions et reçus traçables, pas des paiements par chat.' },
    ],
    protect: ['Choisissez des programmes accrédités aux anciens vérifiables.', 'Vérifiez les émetteurs indépendamment de leur marketing.', 'Ne payez jamais de frais scolaires à des numéros personnels sous pression.'],
    xpReward: 50,
  },
  'sc-deepfake-voice': {
    id: 'sc-deepfake-voice',
    slug: 'deepfake-voice-note',
    title: '« Papa » envoie un message vocal',
    category: 'Social engineering',
    channel: 'Note vocale WhatsApp',
    sender: 'Papa (voix exactement comme lui — stressée, pressée)',
    message: '[Note vocale, 0:19] « Fiston, c’est Papa. J’ai eu un accident, mon téléphone est cassé, c’est le numéro d’un ami. Il me faut 75 000 FCFA pour la clinique TOUT DE SUITE sinon ils ne vont pas me soigner. N’appelle pas maman, elle va paniquer. Envoie sur ce numéro MoMo. »',
    thinkPrompt: 'Ça ressemble exactement à lui. Que peut faire l’IA avec 30 secondes de la voix de quelqu’un — et que prouve encore l’identité ?',
    choices: [
      {
        id: 'send-now',
        text: 'Envoyer l’argent — c’est clairement sa voix',
        verdict: 'unsafe',
        consequenceTitle: 'Envoyé. Papa appelle une heure plus tard, perplexe, depuis son numéro normal.',
        consequence: 'Il était chez lui depuis le début. Le clonage vocal n’a besoin que de secondes d’audio — vidéos d’anniversaire, TikToks, statuts. La voix était parfaite parce qu’elle était construite À PARTIR de lui, pas PAR lui.',
        feedback: 'Une voix familière ne prouve plus l’identité. Les voix clonées portent le bon accent, le bon surnom, la bonne panique — la vérification doit venir d’ailleurs.',
      },
      {
        id: 'codeword',
        text: 'Demander le mot de code familial, puis appeler son vrai numéro en vidéo',
        verdict: 'safe',
        consequenceTitle: 'Aucun mot de code ne vient. Les excuses commencent.',
        consequence: '« Pas le temps pour les jeux ! » — la pression remplace la preuve. Vous appelez le vrai numéro de papa en vidéo : il répond depuis le canapé. Le mot de code familial (convenu il y a des mois « en cas d’urgence ») vient de prouver son utilité.',
        feedback: 'Correct. Mots de code convenus + vidéo en direct sur un numéro CONNU battent les clones vocaux. La pression pour sauter la vérification EST la confirmation.',
      },
      {
        id: 'half-ask',
        text: 'Envoyer un peu d’abord en essayant de le joindre',
        verdict: 'risky',
        consequenceTitle: '« La clinique dit que ça ne suffit pas, complète maintenant. »',
        consequence: 'Un paiement partiel prouve que vous payez sous pression — le script continue simplement. Et personne n’a rien vérifié.',
        feedback: 'Tout montant envoyé sur une voix non vérifiée est perdu. Vérifiez d’abord, toujours entièrement, jamais par tranches.',
      },
    ],
    redFlags: [
      { label: 'Voix parfaite, numéro inconnu', explanation: 'Le clonage explique le paradoxe : sa voix, pas son téléphone.' },
      { label: 'Secret + urgence', explanation: '« N’appelle pas maman » écarte le vérificateur ; « TOUT DE SUITE » écarte la réflexion.' },
      { label: 'Argent vers un tiers', explanation: 'Les vraies urgences passent par des personnes et numéros connus.' },
    ],
    protect: ['Convenez d’un mot de code familial pour les urgences — aujourd’hui, pas pendant.', 'Vérifiez les notes vocales choquantes en vidéo sur un numéro connu.', 'Rappelez-vous : voix, photos et vidéos peuvent désormais être générées.'],
    xpReward: 60,
  },
};
