// Traduction française des scénarios (1re partie : messagerie et social).
// Clé = id du scénario anglais. Voir scenarios-2 fr pour la suite.

import type { Scenario } from './scenarios';

export const scenariosFr: Record<string, Scenario> = {
  'sc-whatsapp-verify': {
    id: 'sc-whatsapp-verify',
    slug: 'whatsapp-verification-scam',
    title: 'Vérification WhatsApp',
    category: 'Everyday scams',
    channel: 'WhatsApp',
    sender: '+237 6XX XXX XXX (numéro inconnu)',
    message: 'URGENT ! Votre compte WhatsApp sera SUSPENDU dans 24 heures pour activité inhabituelle. Vérifiez votre compte ici maintenant : bit.ly/wapp-verify-9x2',
    contextNotes: ['Vous n’avez rien demandé.', 'Le numéro n’est pas dans vos contacts.'],
    thinkPrompt: 'Avant de choisir : qui envoie vraiment ceci, et que veut-on vous faire faire dans la précipitation ?',
    choices: [
      {
        id: 'click',
        text: 'Toucher le lien et saisir mon numéro et mon code',
        verdict: 'unsafe',
        consequenceTitle: 'Vous avez saisi votre numéro et le code à 6 chiffres.',
        consequence: 'Ce code était votre code d’enregistrement WhatsApp. L’arnaqueur enregistre VOTRE numéro sur SON téléphone. Vous êtes déconnecté partout. Il écrit à vos contacts pour demander une aide Mobile Money « urgente » — en votre nom.',
        feedback: 'Les codes d’enregistrement sont les clés du compte. WhatsApp ne les demande jamais via un lien, et les liens raccourcis cachent la vraie destination.',
      },
      {
        id: 'reply',
        text: 'Répondre pour demander si c’est vraiment WhatsApp',
        verdict: 'risky',
        consequenceTitle: 'Vous avez répondu. Ils répondent poliment et accentuent la pression.',
        consequence: '« Oui, ici le service vérification. Votre dossier est urgent — vérifiez dans les 10 minutes ou perdez vos discussions. » Répondre leur a dit que votre numéro est actif et inquiet. La pression continue jusqu’à la faute.',
        feedback: 'Échanger vous maintient dans le piège. Chaque réponse est une information.',
      },
      {
        id: 'forward',
        text: 'Transférer à mes amis pour les prévenir',
        verdict: 'risky',
        consequenceTitle: 'Vos amis reçoivent le message — avec le lien actif.',
        consequence: 'Une amie clique et perd son compte. Les alertes qui propagent le lien actif font le travail de distribution de l’attaquant.',
        feedback: 'Ne transférez jamais de liens frauduleux actifs. Prévenez avec des mots ou une capture, jamais le message cliquable.',
      },
      {
        id: 'verify',
        text: 'Ignorer. Ouvrir WhatsApp et vérifier les paramètres',
        verdict: 'safe',
        consequenceTitle: 'Vous ouvrez WhatsApp directement. Tout est normal.',
        consequence: 'Aucune alerte, aucune suspension, compte en pleine santé. Vous bloquez et signalez le numéro. Il ne se passe rien — c’est exactement la victoire.',
        feedback: 'Correct. L’application officielle est la source de vérité. Signaler + bloquer protège aussi la prochaine personne.',
      },
    ],
    redFlags: [
      { label: 'Urgence + menace', explanation: '« Suspendu en 24 heures » : la pression vous empêche de réfléchir.' },
      { label: 'Expéditeur inconnu', explanation: 'WhatsApp communique via l’application, pas depuis des numéros aléatoires.' },
      { label: 'Lien raccourci', explanation: 'bit.ly cache la vraie destination.' },
      { label: 'Demande de code', explanation: 'Tout chemin finissant par « saisissez le code » offre le compte.' },
    ],
    protect: ['Ne partagez jamais les codes d’enregistrement à 6 chiffres.', 'Vérifiez via l’application officielle, ouverte par vous.', 'Bloquez, signalez, et parlez-en à une personne.'],
    xpReward: 40,
  },
  'sc-momo-reward': {
    id: 'sc-momo-reward',
    slug: 'mobile-money-reward-scam',
    title: 'Récompense Mobile Money',
    category: 'Everyday scams',
    channel: 'SMS',
    sender: 'M0B1LE-M0NEY (écrit avec des zéros)',
    message: 'Félicitations ! Vous avez reçu une récompense Mobile Money de 25 000 FCFA. Composez le *126*9*673211*25000# avec votre PIN pour réclamer avant minuit.',
    thinkPrompt: 'De l’argent jamais gagné, réclamé avec votre PIN, expirant ce soir. Que fait chacun de ces éléments ?',
    choices: [
      {
        id: 'dial',
        text: 'Composer le code et saisir mon PIN pour réclamer',
        verdict: 'unsafe',
        consequenceTitle: 'Vous avez composé. La « réclamation » était un transfert.',
        consequence: 'Le code USSD a envoyé de l’argent DE votre portefeuille vers l’arnaqueur, autorisé par VOTRE PIN. Les transferts Mobile Money sont instantanés et quasiment irréversibles. Les 25 000 FCFA n’ont jamais existé.',
        feedback: 'Un PIN autorise les mouvements DE VOTRE argent. Aucune vraie récompense ne se réclame en saisissant votre PIN.',
      },
      {
        id: 'call',
        text: 'Rappeler le numéro pour confirmer',
        verdict: 'risky',
        consequenceTitle: 'Un « agent » aimable répond et vous guide.',
        consequence: 'L’agent, c’est l’arnaqueur. Il vous guide vers une « validation » — le même transfert, raconté gentiment. Rappeler confirme aussi que votre ligne est active.',
        feedback: 'Les arnaqueurs tiennent leurs propres permanences. Confirmez via le numéro officiel que vous connaissez déjà.',
      },
      {
        id: 'balance',
        text: 'Vérifier mon solde MoMo dans l’application officielle d’abord',
        verdict: 'safe',
        consequenceTitle: 'Solde : inchangé. Aucune récompense nulle part.',
        consequence: 'Les vraies récompenses apparaissent dans votre solde ou vos notifications officielles. Rien n’est arrivé, donc rien n’existe. Vous supprimez le SMS et le signalez comme spam.',
        feedback: 'Correct. Le portefeuille lui-même est la source de vérité.',
      },
    ],
    redFlags: [
      { label: 'Récompense non sollicitée', explanation: 'On ne gagne pas d’argent jamais mérité.' },
      { label: 'PIN dans le parcours', explanation: 'Votre PIN protège VOS fonds. Toute réclamation qui l’exige est un retrait déguisé.' },
      { label: 'Expiration à minuit', explanation: 'La pression empêche la vérification du solde qui trahirait le mensonge.' },
      { label: 'Expéditeur trafiqué', explanation: 'Des zéros au lieu de la lettre O — fait pour tromper d’un coup d’œil.' },
    ],
    protect: ['Votre PIN n’autorise que VOS paiements — jamais pour « recevoir ».', 'Vérifiez le solde officiel avant d’agir sur un message d’argent.', 'Signalez les SMS spam à votre opérateur.'],
    xpReward: 40,
  },
  'sc-mtn-support': {
    id: 'sc-mtn-support',
    slug: 'mtn-support-pin-request',
    title: 'Le « support MTN » veut votre PIN',
    category: 'Everyday scams',
    channel: 'Appel téléphonique',
    sender: 'Appelant se disant du service client MTN',
    message: '« Bonjour, ici le support MTN. Nous migrons le réseau et votre ligne sera bloquée. Confirmez le code que nous venons de vous envoyer pour mettre votre SIM sur liste blanche. » Un code à 4 chiffres arrive par SMS pendant qu’il parle.',
    thinkPrompt: 'C’est lui qui appelle, qui crée l’urgence, et la solution est un code de votre téléphone. Quel problème résout-il vraiment ?',
    choices: [
      {
        id: 'give',
        text: 'Dicter le code pour garder ma ligne active',
        verdict: 'unsafe',
        consequenceTitle: 'Code dicté. L’appel devient silencieux, puis coupe.',
        consequence: 'Ce code autorisait un changement de SIM / une réinitialisation. Dans l’heure, votre ligne ne fonctionne plus et votre Mobile Money est vidé. Le « support » n’a jamais existé.',
        feedback: 'Aucun vrai opérateur ne demande les codes de votre écran. Quiconque le fait usurpe — raccrochez.',
      },
      {
        id: 'hangup-verify',
        text: 'Raccrocher et appeler moi-même le numéro officiel',
        verdict: 'safe',
        consequenceTitle: 'Le service officiel : « Aucune migration, votre ligne va bien. »',
        consequence: 'Cinq minutes sur la vraie helpline confirment la fiction. Le numéro de l’arnaqueur est signalé et bloqué.',
        feedback: 'Correct. Raccrochez, puis vérifiez par un canal QUE VOUS choisissez.',
      },
      {
        id: 'argue',
        text: 'Rester en ligne et discuter avec lui',
        verdict: 'risky',
        consequenceTitle: 'Il reste calme et enchaîne les arguments.',
        consequence: 'Vingt minutes plus tard vous êtes fatigué, et « juste pour prouver que la ligne marche, saisissez… » — l’épuisement fait partie du script.',
        feedback: 'Ne débattez pas avec les arnaqueurs. Chaque minute au téléphone les aide à vous user. Raccrochez.',
      },
    ],
    redFlags: [
      { label: 'Appel de support non sollicité', explanation: 'Les opérateurs n’appellent pas pour des migrations en exigeant des codes.' },
      { label: 'Code de VOTRE téléphone', explanation: 'Les codes reçus vous authentifient VOUS. Les dicter transfère ce pouvoir.' },
      { label: 'Menace de blocage', explanation: 'La peur de perdre votre ligne court-circuite la prudence — c’est voulu.' },
    ],
    protect: ['Raccrochez aux appels de « support » non sollicités.', 'Rappelez uniquement les numéros officiels connus.', 'Ne dictez jamais codes, PIN ni OTP à personne.'],
    xpReward: 40,
  },
  'sc-apk-data': {
    id: 'sc-apk-data',
    slug: 'free-data-apk',
    title: 'L’appli de data gratuite d’un ami',
    category: 'Malware',
    channel: 'WhatsApp (compte d’un ami)',
    sender: 'Votre ami (ou quelqu’un sur son compte)',
    message: 'Frère installe cette appli, ça donne de la data MTN gratuite chaque semaine. J’ai déjà eu la mienne. [FreeData.apk, 8 Mo]',
    thinkPrompt: 'De la data gratuite, hors Play Store, d’un ami qui n’est peut-être pas votre ami. Que vérifier avant d’installer quoi que ce soit ?',
    choices: [
      {
        id: 'install',
        text: 'L’installer — mon ami ne me ferait pas de mal',
        verdict: 'unsafe',
        consequenceTitle: 'Installé. Ça demande l’accès SMS + contacts « pour activer ».',
        consequence: 'C’est un logiciel espion. Il lit vos SMS d’OTP (adieu codes MoMo et banque), téléverse vos contacts, et se transfère à tous vos proches — en votre nom. Le compte de votre ami était piraté.',
        feedback: 'Les APK hors boutiques officielles échappent à tout contrôle. Les applis « gratuites » exigeant l’accès SMS récoltent les OTP.',
      },
      {
        id: 'forward',
        text: 'Le transférer au groupe pour que tout le monde en profite',
        verdict: 'unsafe',
        consequenceTitle: 'Douze personnes l’installent dans l’heure.',
        consequence: 'Vous venez de devenir le canal de distribution. Le malware vous remercie en s’envoyant depuis chaque téléphone infecté — dont le vôtre.',
        feedback: 'Transférer des APK non vérifiés multiplie le mal. Une installation, une victime ; un transfert, une épidémie.',
      },
      {
        id: 'verify',
        text: 'Appeler mon ami et vérifier sur le Play Store d’abord',
        verdict: 'safe',
        consequenceTitle: 'Au téléphone, votre ami est perplexe — il n’a rien envoyé.',
        consequence: 'Son compte a été piraté la nuit dernière. Cette appli n’existe pas sur le Play Store. Vous prévenez le groupe AVEC DES MOTS, il récupère son compte, personne n’installe rien.',
        feedback: 'Correct. Vérifiez l’expéditeur sur un autre canal, et n’installez que depuis les boutiques officielles.',
      },
    ],
    redFlags: [
      { label: 'APK hors boutique', explanation: 'Les applis chargées à côté échappent à tout contrôle anti-malware.' },
      { label: 'Cadeau trop beau', explanation: '« Data gratuite chaque semaine », c’est l’appât calibré pour voyager vite.' },
      { label: 'Accès SMS + contacts', explanation: 'Pour une appli data, une seule raison : vol d’OTP et propagation.' },
      { label: 'Expéditeur peut-être piraté', explanation: 'Les comptes de confiance sont détournés justement pour envoyer des malwares.' },
    ],
    protect: ['Installez uniquement depuis Play Store / App Store.', 'Refusez SMS et contacts aux applis qui n’en ont pas besoin.', 'Vérifiez les messages surprenants sur un autre canal.'],
    xpReward: 50,
  },
  'sc-friend-emergency': {
    id: 'sc-friend-emergency',
    slug: 'friend-emergency-money',
    title: 'Un « ami » a besoin d’argent urgent',
    category: 'Social engineering',
    channel: 'WhatsApp',
    sender: 'Ami d’enfance (nouveau numéro : « j’ai perdu mon téléphone »)',
    message: 'Frère stp je suis à l’hôpital avec maman, la facture c’est 50 000 et on ne va pas la soigner. Envoie 20 000 MoMo à ce numéro stp, je te rembourse demain matin. Dis à personne, j’ai honte.',
    thinkPrompt: 'Vraie urgence ou urgence scénarisée ? Quels détails vérifier sans envoyer d’argent ?',
    choices: [
      {
        id: 'send',
        text: 'Envoyer les 20 000 aussitôt — urgence familiale d’abord',
        verdict: 'unsafe',
        consequenceTitle: 'Envoyé. « Merci frère, remboursement demain. » Demain ne vient jamais.',
        consequence: 'Le numéro devient silencieux. Votre vrai ami, joint le lendemain, ignore tout de tout hôpital. L’histoire — hôpital, honte, secret, délai — était assemblée pour rendre la vérification impolie.',
        feedback: 'Urgence + secret = signature de l’arnaque sentimentale. Les vraies urgences survivent à 2 minutes de vérification.',
      },
      {
        id: 'call',
        text: 'Appeler son ancien numéro et la famille avant tout envoi',
        verdict: 'safe',
        consequenceTitle: 'Son ancien numéro décroche. Il est chez lui, en pleine santé.',
        consequence: 'Son ancien compte avait été piraté il y a des mois et dormait. Vous signalez le nouveau numéro, prévenez les amis communs, et zéro franc ne bouge.',
        feedback: 'Correct. Vérifiez sur un canal que l’arnaqueur ne contrôle pas. L’argent peut attendre deux minutes ; les arnaques, non.',
      },
      {
        id: 'half',
        text: 'Envoyer la moitié pour aider, vérifier après',
        verdict: 'risky',
        consequenceTitle: 'Vous envoyez 10 000 « de bonne foi ».',
        consequence: 'Puis vient le deuxième acte : « l’hôpital dit que 10 000 ne suffit pas, complète. » Un paiement partiel prouve que vous payez — jamais l’histoire.',
        feedback: 'Moitié d’arnaque reste une arnaque. La vérification vient AVANT tout montant.',
      },
    ],
    redFlags: [
      { label: 'Nouveau numéro + téléphone perdu', explanation: 'Le montage classique pour expliquer l’injoignable « vrai » lui.' },
      { label: 'Demande de secret', explanation: '« Ne dis à personne » écarte celui qui repérerait le mensonge.' },
      { label: 'Promesse de remboursement', explanation: 'Le remboursement de demain ne coûte rien à l’arnaqueur aujourd’hui.' },
    ],
    protect: ['Vérifiez les urgences sur un canal connu avant d’envoyer de l’argent.', 'Traitez les demandes de secret comme un drapeau rouge.', 'Si un ami est piraté, aidez-le à récupérer — ne payez pas le pirate.'],
    xpReward: 40,
  },
  'sc-fb-login': {
    id: 'sc-fb-login',
    slug: 'facebook-login-alert',
    title: 'Alerte de connexion Facebook',
    category: 'Account security',
    channel: 'SMS + lien',
    sender: 'Sécurité Faceb00k (SMS)',
    message: 'Votre compte Facebook a été connecté depuis Douala sur un nouvel appareil. Si ce n’était PAS vous, sécurisez votre compte maintenant : faceb00k-secure.com/login',
    thinkPrompt: 'L’alerte semble réelle car les connexions SONT signalées. Qu’est-ce qui sépare ce message d’un vrai ?',
    choices: [
      {
        id: 'login-link',
        text: 'Ouvrir le lien et me connecter pour sécuriser mon compte',
        verdict: 'unsafe',
        consequenceTitle: 'La page ressemble exactement à Facebook. Vous vous connectez.',
        consequence: 'C’était un faux parfait sur faceb00k-secure.com. Votre mot de passe et votre session appartiennent à quelqu’un d’autre, qui vous éjecte et arnaque vos amis dans l’heure.',
        feedback: 'Domaines sosies (faceb00k avec des zéros) + formulaire = récolte d’identifiants. Naviguez vous-même vers l’appli.',
      },
      {
        id: 'app-check',
        text: 'Ouvrir moi-même l’appli Facebook et vérifier les sessions',
        verdict: 'safe',
        consequenceTitle: 'Paramètres > Sécurité : uniquement vos appareils. Aucune connexion à Douala.',
        consequence: 'Il n’y a jamais eu de connexion — le SMS l’a inventée. Vous activez l’authentification à deux facteurs au passage, et signalez le SMS.',
        feedback: 'Correct. La liste des sessions dans l’appli est la vérité terrain.',
      },
      {
        id: 'ignore-all',
        text: 'Tout ignorer et ne rien changer',
        verdict: 'risky',
        consequenceTitle: 'Cette fois c’était faux. Il ne se passe rien.',
        consequence: 'Mais tout ignorer TOUJOURS est dangereux aussi — un jour une vraie alerte arrivera et vous la ferez défiler. La bonne habitude : vérifier dans l’appli, pas ignorer.',
        feedback: 'Ignorer a marché par chance. Construisez l’habitude de vérification.',
      },
    ],
    redFlags: [
      { label: 'Domaine sosie', explanation: 'faceb00k-secure.com n’est pas facebook.com — des zéros pour la lettre O.' },
      { label: 'Incident inventé', explanation: 'La « connexion à Douala » n’a jamais eu lieu ; les détails rendent les mensonges crédibles.' },
      { label: 'Connexion via lien', explanation: 'Les vraies plateformes disent « ouvrez votre appli », jamais « connectez-vous ici ».' },
    ],
    protect: ['Tapez facebook.com vous-même ou utilisez l’appli — jamais le lien.', 'Vérifiez les sessions actives et activez la double authentification.', 'Chaque alerte = vérifier, jamais cliquer.'],
    xpReward: 50,
  },
  'sc-wifi-twin': {
    id: 'sc-wifi-twin',
    slug: 'cafe-wifi-twin',
    title: 'Le Wi-Fi du café qui veut votre login',
    category: 'Safe browsing',
    channel: 'En personne (café)',
    sender: 'Liste des réseaux : « CAFE_FREE_WIFI_FAST » (ouvert, signal fort)',
    message: 'Vous rejoignez. Une page de connexion s’ouvre : « Bienvenue ! Connectez-vous avec votre compte Google ou Facebook pour profiter du Wi-Fi gratuit. » Le vrai Wi-Fi du café, écrit au mur, s’appelle « Cafe_Noura_2024 » (verrouillé, mot de passe sur le ticket).',
    thinkPrompt: 'Deux réseaux, dont un qui veut votre login social. De quoi un hotspot a-t-il légitimement besoin ?',
    choices: [
      {
        id: 'google-login',
        text: 'Me connecter avec Google — j’ai besoin d’internet',
        verdict: 'unsafe',
        consequenceTitle: 'La page accepte tout et vous connecte.',
        consequence: 'C’était un hotspot jumeau malveillant depuis un portable au fond. Vos identifiants Google sont partis chez lui, et tout votre trafic passe par l’attaquant. « Ça a marché », c’est exactement le piège.',
        feedback: 'Les portails Wi-Fi ne demandent jamais votre mot de passe Google ou Facebook. Un formulaire = récolte d’identifiants avec internet gratuit en appât.',
      },
      {
        id: 'ask-staff',
        text: 'Demander au personnel le vrai réseau, utiliser mes données en attendant',
        verdict: 'safe',
        consequenceTitle: 'Le personnel montre le mur : celui verrouillé avec mot de passe sur ticket.',
        consequence: 'Vous rejoignez le vrai réseau, et le faux portail ne vous voit jamais.',
        feedback: 'Correct. Le personnel connaît son réseau. En cas de doute, les données mobiles battent le Wi-Fi mystère.',
      },
      {
        id: 'bank-quick',
        text: 'Se connecter au réseau ouvert mais juste « vérifier vite ma banque »',
        verdict: 'risky',
        consequenceTitle: 'La page banque s’affiche. Tout va bien ?',
        consequence: 'Peut-être — ou peut-être que votre session a été reniflée sur un réseau non chiffré tenu par un attaquant. La banque sur Wi-Fi inconnu joue le compte qui détient votre argent.',
        feedback: 'Jamais de banque sur Wi-Fi public non vérifié. Attendez une connexion de confiance.',
      },
    ],
    redFlags: [
      { label: 'Login social pour du Wi-Fi', explanation: 'Les hotspots demandent au plus un code — jamais votre mot de passe Google/Facebook.' },
      { label: 'Nom différent', explanation: 'Le vrai réseau est au mur ; le tentant ne l’est pas.' },
      { label: 'Ouvert + signal fort', explanation: 'Les attaquants diffusent des réseaux ouverts bruyants pour attirer.' },
    ],
    protect: ['Confirmez les noms de hotspots avec le personnel.', 'Ne saisissez jamais de vrais mots de passe dans les portails.', 'Données mobiles pour la banque ; OS et applis à jour.'],
    xpReward: 40,
  },
};
