// Traduction française des scénarios (2e partie : emploi, école, web, comptes).

import type { Scenario } from './scenarios';

export const scenariosFr2: Record<string, Scenario> = {
  'sc-hr-fee': {
    id: 'sc-hr-fee',
    slug: 'hr-processing-fee-job',
    title: 'Les RH demandent des frais de dossier',
    category: 'Job scams',
    channel: 'Telegram',
    sender: '« Sarah, RH » d’une entreprise de logistique (sur Telegram depuis un mois)',
    message: 'Félicitations ! Retenu pour le poste de Saisie de données : 150 000 FCFA/mois, à distance, sans entretien. Pour traiter votre dossier, envoyez 10 000 FCFA sur ce numéro MoMo aujourd’hui. Les places ferment ce soir.',
    thinkPrompt: 'Un salaire, sans entretien, et C’EST VOUS qui payez — ce soir. Dans quel sens circule l’argent dans une vraie embauche ?',
    choices: [
      {
        id: 'pay',
        text: 'Payer les 10 000 FCFA — le salaire en vaut la peine',
        verdict: 'unsafe',
        consequenceTitle: 'Payé. « Ensuite : 15 000 pour le certificat médical. »',
        consequence: 'Puis des frais d’uniforme, de formation… chaque étape assez petite pour sembler récupérable, jusqu’à 60 000 FCFA envolés et « Sarah » supprime son compte. Les vrais employeurs ne facturent jamais l’embauche.',
        feedback: 'Des frais-pour-être-embauché, c’est toute l’arnaque. L’argent circule employeur-vers-vous, jamais l’inverse.',
      },
      {
        id: 'verify',
        text: 'Demander un contrat et vérifier l’entreprise en indépendant',
        verdict: 'safe',
        consequenceTitle: 'Le vrai site de l’entreprise ne liste aucun poste — et alerte sur les arnaqueurs Telegram.',
        consequence: 'Vous trouvez leur page carrières officielle et un avertissement décrivant le même script. Vous signalez le compte et gardez vos 10 000.',
        feedback: 'Correct. Une vraie embauche survit à la vérification : site officiel, numéro public, contrat écrit.',
      },
      {
        id: 'id-first',
        text: 'Envoyer d’abord pièce d’identité et diplôme pour « bloquer la place »',
        verdict: 'risky',
        consequenceTitle: 'Place « bloquée ». La demande de frais arrive quand même.',
        consequence: 'Pire : ils détiennent votre photo d’identité et votre diplôme, utilisables pour usurpation et pour arnaquer d’autres en VOTRE nom.',
        feedback: 'Les documents d’abord, c’est aussi une perte. Pièce + diplôme = usurpation d’identité même sans paiement.',
      },
    ],
    redFlags: [
      { label: 'Embauche sans entretien', explanation: 'Personne ne paie 150 000/mois sans vous rencontrer.' },
      { label: 'Frais pour être embauché', explanation: 'Frais de dossier, médicaux, d’uniforme exigés des candidats = schéma d’arnaque.' },
      { label: 'Délai de ce soir', explanation: 'La fausse urgence bloque la vérification qui tuerait l’affaire.' },
      { label: 'RH sur Telegram uniquement', explanation: 'Compte récent, pas d’email d’entreprise, identité invérifiable.' },
    ],
    protect: ['Ne payez jamais pour être embauché.', 'Vérifiez les offres sur les sites officiels et numéros publics.', 'N’envoyez jamais de pièces d’identité par chat à des recruteurs non vérifiés.'],
    xpReward: 50,
  },
  'sc-exam-portal': {
    id: 'sc-exam-portal',
    slug: 'exam-results-portal',
    title: 'Consultez vos résultats d’examen ici',
    category: 'Student scams',
    channel: 'Groupe WhatsApp de classe',
    sender: 'Transféré de nombreuses fois : « Portail OFFICIEL des résultats — vérifiez avant fermeture ! »',
    message: 'Les résultats sont là ! Saisissez votre numéro de candidat ET votre mot de passe email scolaire pour voir vos notes avant la fermeture du portail : results-check-2026.com',
    thinkPrompt: 'L’excitation des résultats plus un champ mot de passe. Quand votre école a-t-elle eu besoin de votre mot de passe email pour afficher des notes ?',
    choices: [
      {
        id: 'enter',
        text: 'Saisir mon numéro de candidat et mon mot de passe email',
        verdict: 'unsafe',
        consequenceTitle: 'La page tourne… puis affiche une erreur. « Réessayez plus tard. »',
        consequence: 'Votre mot de passe email scolaire est récolté. Cette boîte mail réinitialise tout le reste : réseaux sociaux, codes MoMo, portails scolaires. Des jours plus tard, vos camarades reçoivent des arnaques « de votre part ».',
        feedback: 'Aucun portail de résultats ne demande votre mot de passe EMAIL. Le numéro de candidat suffit sur les vrais portails.',
      },
      {
        id: 'school-site',
        text: 'Aller moi-même sur le site de l’école / de l’office des examens',
        verdict: 'safe',
        consequenceTitle: 'Site officiel de l’office : « Résultats publiés vendredi. »',
        consequence: 'Les résultats ne sont même pas sortis — le portail transféré était pure fiction. Vous prévenez le groupe avec une capture (lien retiré) et l’admin supprime le message.',
        feedback: 'Correct. Les offices annoncent publiquement les dates. « Avant fermeture » est une fiction pour battre l’annonce.',
      },
      {
        id: 'friend-pass',
        text: 'Demander à un ami qui a « vérifié » son login à emprunter',
        verdict: 'risky',
        consequenceTitle: 'Votre amie partage son mot de passe pour « voir à quoi ça ressemble ».',
        consequence: 'Deux comptes compromis désormais, et vous avez normalisé le partage de mots de passe dans votre classe.',
        feedback: 'Les mots de passe empruntés doublent les dégâts. Vérifiez le portail, pas le login.',
      },
    ],
    redFlags: [
      { label: 'Mot de passe pour des notes', explanation: 'Les vrais portails demandent des numéros de candidat, pas des mots de passe email.' },
      { label: 'Frénésie de transferts', explanation: '« Transféré partout » + fermeture imminente = bousculade fabriquée.' },
      { label: 'Portail hors domaine', explanation: 'results-check-2026.com n’est pas le domaine de votre office d’examens.' },
    ],
    protect: ['N’utilisez que le site officiel de l’office, trouvé via recherche ou avis scolaire.', 'Ne saisissez jamais de mots de passe email sur des pages tierces.', 'Prévenez les groupes avec des captures, jamais en transférant le lien.'],
    xpReward: 50,
  },
  'sc-internship': {
    id: 'sc-internship',
    slug: 'paid-internship-abroad',
    title: 'Stage rémunéré à l’étranger',
    category: 'Job scams',
    channel: 'Message LinkedIn',
    sender: 'Recruteur au profil soigné (500+ relations, bannière de bureaux en banque d’images)',
    message: 'Votre profil est impressionnant ! Stage rémunéré de 3 mois à Dubaï : vols + indemnité 300 000 FCFA/mois. Réglez juste le traitement visa (45 000 FCFA) via notre agent agréé cette semaine.',
    thinkPrompt: 'Prestige, voyage, indemnité — et un paiement via « leur » agent. Que ferait différemment une vraie multinationale ?',
    choices: [
      {
        id: 'agent',
        text: 'Payer l’agent — opportunité Dubaï unique',
        verdict: 'unsafe',
        consequenceTitle: 'Reçu reçu. Puis : « frais d’ambassade », « frais d’assurance »…',
        consequence: 'Chaque frais en débloque un plus gros jusqu’à 150 000 FCFA envolés et le profil du recruteur qui disparaît. Les relations LinkedIn s’achètent ; les bureaux se téléchargent.',
        feedback: 'Les vrais employeurs utilisent les circuits visa officiels et ne routent jamais de paiements via des agents privés sous délai.',
      },
      {
        id: 'verify-co',
        text: 'Vérifier l’entreprise, le poste et l’agent en indépendant',
        verdict: 'safe',
        consequenceTitle: 'La vraie entreprise répond : « Nous n’avons aucun programme de ce type. »',
        consequence: 'Un email à leur contact public expose toute l’affaire. Le faux profil est signalé, et vos économies restent à vous.',
        feedback: 'Correct. Vérifiez les trois : entreprise (site officiel), poste (annonce officielle), agent (listes officielles).',
      },
      {
        id: 'passport',
        text: 'Envoyer la copie du passeport pour « réserver » le temps de réfléchir',
        verdict: 'risky',
        consequenceTitle: '« Réservé ! » La pression pour payer double désormais.',
        consequence: 'Vos données passeport circulent : usurpation, faux comptes à votre nom, et levier (« on a vos documents, payez ou else » — payez ou sinon).',
        feedback: 'Les copies de passeport sont de l’or pour les criminels. Jamais à des contacts non vérifiés.',
      },
    ],
    redFlags: [
      { label: 'Frais de visa/agent initiaux', explanation: 'Les programmes légitimes déduisent des indemnités ou passent par circuits officiels.' },
      { label: 'Offre prestigieuse non sollicitée', explanation: 'Les stages Dubaï tombés du ciel ciblent l’ambition, pas les qualifications.' },
      { label: 'Profil soigné mais creux', explanation: 'Relations et bannières sont bon marché ; un historique vérifiable ne l’est pas.' },
    ],
    protect: ['Vérifiez via le contact officiel — jamais les liens du recruteur.', 'Ne payez jamais d’agents pour des visas d’emploi sur des délais de chat.', 'Gardez passeports et pièces comme du liquide.'],
    xpReward: 50,
  },
  'sc-password-reuse': {
    id: 'sc-password-reuse',
    slug: 'one-password-everywhere',
    title: 'Un seul mot de passe partout',
    category: 'Account security',
    channel: 'Situation racontée (votre habitude)',
    sender: 'Vous, par efficacité',
    message: 'Vous utilisez « Lionel1999! » pour l’email, Facebook, MoMo, le portail scolaire et des sites de paris. Un jour, un petit forum rejoint en 2022 est piraté. Votre email + mot de passe circulent dans une liste fuitée sur Telegram.',
    thinkPrompt: 'Rien d’« important » n’a été piraté — juste un vieux forum. Pourquoi est-ce le scénario le plus dangereux ici ?',
    choices: [
      {
        id: 'nothing',
        text: 'Ignorer — ce forum ne signifie rien pour moi',
        verdict: 'unsafe',
        consequenceTitle: 'Des semaines plus tard : des emails de réinitialisation non demandés.',
        consequence: 'Bourrage d’identifiants : les attaquants rejouent votre paire fuitée contre email, Facebook et MoMo. Même mot de passe partout = une fuite ouvre toutes les portes.',
        feedback: 'Les fuites sont normales désormais. La question n’est jamais SI un mot de passe fuit — mais s’il ouvre autre chose.',
      },
      {
        id: 'change-all',
        text: 'Changer ce mot de passe partout et activer la MFA',
        verdict: 'safe',
        consequenceTitle: 'Nouveaux mots de passe uniques via gestionnaire + MFA sur l’email d’abord.',
        consequence: 'Le mot de passe fuité devient une clé morte. Les attaquants l’essaient sur cinquante sites et il n’ouvre rien. Dégâts totaux : zéro.',
        feedback: 'Correct. Les mots de passe uniques confinent les fuites ; la MFA sur l’email protège la clé maîtresse.',
      },
      {
        id: 'tweak',
        text: 'Ajouter « 123 » à la fin partout — suffisant',
        verdict: 'risky',
        consequenceTitle: '« Lionel1999!123 » partout. Les attaquants essaient les variantes automatiquement.',
        consequence: 'Les outils de bourrage mutent les mots de passe par défaut (chiffres, majuscules). Les retouches prévisibles tombent en minutes.',
        feedback: 'Les changements prévisibles se devinent par machine. Un mot de passe aléatoire unique par site est la vraie correction.',
      },
    ],
    redFlags: [
      { label: 'Identifiant réutilisé', explanation: 'Une fuite = tous les comptes, quand les mots de passe correspondent.' },
      { label: 'Pas de MFA', explanation: 'Sans second facteur, un mot de passe seul = accès total.' },
      { label: 'Vieux comptes oubliés', explanation: 'Les forums oubliés détiennent la clé que vous réutilisez.' },
    ],
    protect: ['Un gestionnaire : un mot de passe aléatoire unique par site.', 'MFA sur l’email d’abord, puis banque, MoMo, réseaux.', 'Après une fuite, changez ce mot de passe partout où il servait.'],
    xpReward: 40,
  },
  'sc-giveaway': {
    id: 'sc-giveaway',
    slug: 'influencer-giveaway-fee',
    title: 'Jeu-concours d’influenceur (payer la livraison)',
    category: 'Everyday scams',
    channel: 'Instagram',
    sender: 'Compte avec les photos d’un influenceur, 800 abonnés, « JEU-CONCOURS finit ce soir »',
    message: 'FÉLICITATIONS ! Vous avez gagné le jeu iPhone 15. Payez 5 000 FCFA de livraison via MoMo à ce numéro sous 2 heures pour recevoir votre lot.',
    thinkPrompt: 'Vous avez gagné sans participer, d’un compte à 800 abonnés, et le lot exige VOTRE paiement. Comptez les drapeaux.',
    choices: [
      {
        id: 'pay-ship',
        text: 'Payer les 5 000 FCFA de livraison — un iPhone vaut bien plus',
        verdict: 'unsafe',
        consequenceTitle: 'Payé. « Frais de douane ensuite : 12 000 FCFA. »',
        consequence: 'L’iPhone n’a jamais existé. L’échelle des frais continue jusqu’à votre arrêt — chaque marche « petite face à un iPhone ». Le compte vous bloque après le troisième paiement.',
        feedback: 'Les lots n’exigent jamais de paiements du gagnant. Frais de port/douane/vérification = arnaque aux frais avancés.',
      },
      {
        id: 'check-real',
        text: 'Vérifier le vrai compte certifié de l’influenceur',
        verdict: 'safe',
        consequenceTitle: 'Vrai compte (2 M d’abonnés) : aucun jeu, plus un avertissement anti-arnaque.',
        consequence: 'Le vrai influenceur a posté le mois dernier : « Des faux comptes font des jeux à mon nom. » Vous signalez l’usurpateur en deux gestes.',
        feedback: 'Correct. Abonnés, badge certifié et publications du vrai compte démasquent les usurpateurs.',
      },
      {
        id: 'tag-friend',
        text: 'Identifier des amis pour qu’ils gagnent aussi',
        verdict: 'risky',
        consequenceTitle: 'Trois amis « gagnent » dans l’heure.',
        consequence: 'Identifier recrute des victimes pour l’arnaqueur et dépense votre crédibilité. Vos amis perdent de l’argent parce que vous avez cautionné d’un tag.',
        feedback: 'N’amplifiez jamais des jeux non vérifiés. Les tags sont des cautions — vérifiez avant de les dépenser.',
      },
    ],
    redFlags: [
      { label: 'Gain sans participation', explanation: 'Les gains non sollicités sont toujours faux.' },
      { label: 'Frais pour recevoir', explanation: 'Les vrais lots déduisent ou sont gratuits — jamais de MoMo vers un numéro.' },
      { label: 'Compte usurpateur', explanation: 'Photos volées, peu d’abonnés, bio pressante.' },
      { label: 'Délai de 2 heures', explanation: 'La vitesse empêche la seule vérification qui tue l’arnaque.' },
    ],
    protect: ['Vérifiez les jeux sur le vrai compte certifié.', 'Ne payez jamais de frais pour recevoir des lots.', 'Signalez les usurpateurs au lieu d’identifier des amis.'],
    xpReward: 40,
  },
  'sc-qr-menu': {
    id: 'sc-qr-menu',
    slug: 'qr-menu-sticker',
    title: 'QR du menu avec un autocollant dessus',
    category: 'Safe browsing',
    channel: 'En personne (restaurant)',
    sender: 'QR de table avec un autocollant légèrement de travers sur l’original',
    message: 'Vous scannez. Votre navigateur ouvre « menu-restaurant-pay.com » qui demande de « se connecter avec Google pour voir le menu et payer depuis votre table ».',
    thinkPrompt: 'Un menu qui exige votre login Google. Quel rapport entre des prix et votre compte Google ?',
    choices: [
      {
        id: 'login-pay',
        text: 'Me connecter avec Google et payer — c’est pratique',
        verdict: 'unsafe',
        consequenceTitle: 'Connecté. Le menu fonctionne même !',
        consequence: 'L’autocollant était un recouvrement malveillant. Vos identifiants Google sont partis chez l’attaquant, qui possède désormais votre email — et via lui, les réinitialisations de tout. Le menu qui marche était le camouflage.',
        feedback: 'Les menus n’exigent jamais de login Google. Les autocollants sur QR sont une attaque connue — le recouvrement mène à la récolte d’identifiants.',
      },
      {
        id: 'ask-staff',
        text: 'Demander le vrai menu au personnel et vérifier l’URL',
        verdict: 'safe',
        consequenceTitle: 'Le personnel décolle l’autocollant : URL différente dessous.',
        consequence: 'Le vrai QR avait été remplacé le matin même. Le personnel retire tous les autocollants, vous commandez normalement, et l’attaquant ne reçoit rien de votre table.',
        feedback: 'Correct. Vérifiez les codes physiques comme les numériques : comparez avec le personnel, prévisualisez les URL.',
      },
      {
        id: 'photo-later',
        text: 'Photographier le QR et le scanner chez moi en Wi-Fi',
        verdict: 'risky',
        consequenceTitle: 'À la maison, même fausse page, même demande de login.',
        consequence: 'Le lieu n’a jamais compté — la destination était malveillante partout où vous l’ouvrez. Retarder ne désinfecte pas un mauvais lien.',
        feedback: 'Une destination malveillante l’est partout. Vérifiez la SOURCE, pas le réseau.',
      },
    ],
    redFlags: [
      { label: 'Code trafiqué', explanation: 'Autocollant de travers sur l’original = destination remplacée.' },
      { label: 'Login pour un menu', explanation: 'Aucun menu légitime ne demande votre compte Google.' },
      { label: 'Domaine sosie de paiement', explanation: 'menu-restaurant-pay.com n’est pas le site du restaurant.' },
    ],
    protect: ['Inspectez les QR (autocollants), confirmez avec le personnel.', 'Prévisualisez les URL avant d’ouvrir ; jamais de login depuis des QR aléatoires.', 'Tapez vous-même les adresses de paiement.'],
    xpReward: 40,
  },
  'sc-attachment-invoice': {
    id: 'sc-attachment-invoice',
    slug: 'invoice-attachment-email',
    title: 'Facture impayée en pièce jointe',
    category: 'Email threats',
    channel: 'Email',
    sender: '« Service Facturation » <billing@acme-corp-invoices.com>',
    message: 'Objet : Facture #INV-0451 EN RETARD — suspension sous 24 h. « Voir la facture jointe et payer pour éviter l’interruption. » Pièce jointe : Invoice-0451.html (47 Ko). Vous n’avez jamais entendu parler d’Acme Corp.',
    thinkPrompt: 'Une facture d’une société inconnue, avec pièce HTML et menace de 24 h. À QUOI sert la pièce jointe ?',
    choices: [
      {
        id: 'open',
        text: 'Ouvrir la pièce jointe pour voir ce que je devrais',
        verdict: 'unsafe',
        consequenceTitle: 'La « facture » s’ouvre dans votre navigateur et demande un login email « pour voir ».',
        consequence: 'Les pièces HTML affichent de fausses pages de login qui volent les mots de passe — et peuvent porter des malwares. La curiosité sur une dette inexistante vient de coûter de vrais mots de passe.',
        feedback: 'Les pièces jointes inattendues sont la charge, pas l’information. Expéditeur inconnu + dette inconnue = supprimer.',
      },
      {
        id: 'pay-call',
        text: 'Appeler le numéro dans la pièce jointe pour contester',
        verdict: 'risky',
        consequenceTitle: 'Un « agent facturation » répond et propose de « vérifier votre compte ».',
        consequence: 'Le numéro appartient aux arnaqueurs. L’appel de contestation devient une séance d’ingénierie sociale qui récolte vos données avec patience.',
        feedback: 'Les coordonnées dans un message frauduleux appartiennent à la fraude. Contestez via des numéros trouvés indépendamment.',
      },
      {
        id: 'delete-report',
        text: 'Supprimer et signaler comme hameçonnage — je ne dois rien à Acme',
        verdict: 'safe',
        consequenceTitle: 'Supprimé, signalé. Rien dû, rien ouvert.',
        consequence: 'Tout reposait sur la panique d’une fausse dette. Votre règle — pas de relation, pas de paiement, pas d’ouverture — règle ça en dix secondes.',
        feedback: 'Correct. Société inconnue + pièce inattendue + urgence = signaler et supprimer, sans échanger.',
      },
    ],
    redFlags: [
      { label: 'Facturier inconnu', explanation: 'On ne doit rien à une société jamais utilisée.' },
      { label: 'Pièce HTML', explanation: 'Les factures sont des PDF ; les .html ouvrent des pages de récolte.' },
      { label: 'Menace de suspension', explanation: 'Les menaces de 24 h fabriquent la panique qui ouvre les pièces.' },
    ],
    protect: ['N’ouvrez jamais de pièces inattendues — surtout .html, .doc à macros, .apk.', 'Vérifiez les dettes via les sociétés réellement utilisées, par canaux officiels.', 'Signalez l’hameçonnage au lieu de le contester avec l’expéditeur.'],
    xpReward: 50,
  },
  'sc-fake-profile': {
    id: 'sc-fake-profile',
    slug: 'fake-profile-friend-request',
    title: 'Nouvelle « vieille amie » sans historique',
    category: 'Social engineering',
    channel: 'Facebook / Instagram',
    sender: 'Demande d’amie de « Clarisse M. » — même nom et photos que votre ancienne camarade',
    message: 'Salut ! J’ai perdu l’accès à mon ancien compte, voici mon nouveau. Comment tu vas ?? Tu peux me rendre un petit service — j’ai besoin de ton aide pour voter pour mon cousin à un concours, envoie-moi juste le code que tu vas recevoir.',
    thinkPrompt: 'Même visage, nouveau compte, petit service avec un code. Que prouverait que c’est vraiment Clarisse ?',
    choices: [
      {
        id: 'code',
        text: 'Envoyer le code pour l’aider au concours',
        verdict: 'unsafe',
        consequenceTitle: 'Code envoyé. Déconnecté quelques minutes plus tard.',
        consequence: 'Le « code du concours » était VOTRE code de réinitialisation. Le profil était un clone — mêmes photos, zéro historique partagé. Votre compte spamme désormais le même concours à VOS amis.',
        feedback: 'Les profils clones récoltent photos et noms, puis arment la confiance. Les codes envoyés autorisent toujours quelque chose contre vous.',
      },
      {
        id: 'quiz-her',
        text: 'Poser une question que seule la vraie Clarisse connaît, sur un autre canal',
        verdict: 'safe',
        consequenceTitle: 'La vraie Clarisse répond : « Ce n’est pas moi — signale-le. »',
        consequence: 'Une question sur votre passé commun — posée via son numéro connu — fait s’effondrer l’usurpation. Le clone est signalé par vous deux.',
        feedback: 'Correct. Secrets partagés + canal indépendant battent l’usurpation. Les photos ne prouvent rien.',
      },
      {
        id: 'accept-chat',
        text: 'Accepter et discuter un moment pour « être sûr »',
        verdict: 'risky',
        consequenceTitle: 'Discussion amicale pendant trois jours. Puis la faveur arrive.',
        consequence: 'La patience est la méthode : d’abord le lien, ensuite la demande. Au moment du code, refuser semble impoli — c’était le plan.',
        feedback: 'Discuter ne vérifie pas l’identité ; ça construit la confiance que l’arnaque dépensera. Vérifiez d’abord, discutez après.',
      },
    ],
    redFlags: [
      { label: 'Marqueurs de clone', explanation: 'Mêmes photos, compte récent, peu d’amis, aucun historique ni tags partagés.' },
      { label: 'Faveur avec un code', explanation: 'Les votes de concours n’exigent jamais de codes DE VOTRE téléphone.' },
      { label: 'Recontact non sollicité', explanation: 'Contact sorti de nulle part + petite demande rapide = la mise en place.' },
    ],
    protect: ['Inspectez les nouveaux profils : âge, amis, historique, tags.', 'Vérifiez l’identité avec des souvenirs partagés sur un autre canal.', 'Signalez les clones ; prévenez les amis communs avec des mots, pas des transferts.'],
    xpReward: 50,
  },
  'sc-fake-certificate': {
    id: 'sc-fake-certificate',
    slug: 'fake-certificate-course',
    title: 'Payer un certificat, sauter la formation',
    category: 'Student scams',
    channel: 'Publicité Instagram + WhatsApp',
    sender: '« Global Skills Academy » — page pro, des certificats dans chaque post',
    message: 'Obtenez un Diplôme CERTIFIÉ en Marketing Digital en 48 heures — sans cours, sans examens. 25 000 FCFA seulement. Les employeurs vérifient nos certificats en ligne ! Payez via MoMo pour vous inscrire.',
    thinkPrompt: 'Un diplôme sans apprentissage, vérifié « en ligne », payable par MoMo. Qui reconnaît vraiment ce certificat ?',
    choices: [
      {
        id: 'pay-cert',
        text: 'Payer — un certificat booste vite mon CV',
        verdict: 'unsafe',
        consequenceTitle: 'Certificat PDF reçu. Il a l’air officiel.',
        consequence: 'Le « portail de vérification » est leur propre site qui affiche ce qu’ils tapent. Les vrais employeurs vérifient auprès d’organismes accrédités, pas de pages de diplômés. Vous avez payé 25 000 FCFA pour un PDF et un mensonge sur votre CV — qui peut coûter de vrais emplois.',
        feedback: 'Des diplômes sans apprentissage sont du papier, et du faux papier frôle la fraude. Les employeurs vérifient auprès des émetteurs, pas de leurs sites.',
      },
      {
        id: 'check-accredit',
        text: 'Vérifier l’accréditation auprès d’employeurs et organismes officiels',
        verdict: 'safe',
        consequenceTitle: 'Aucune accréditation nulle part. Aucun employeur ne les connaît.',
        consequence: 'Une recherche rapide plus une question à un professionnel révèle zéro reconnaissance. La « académie » n’existe que comme page et numéro MoMo. Votre argent reste à vous.',
        feedback: 'Correct. Vérifiez les diplômes comme les employeurs : accréditation indépendante, émetteurs reconnus, vrais anciens.',
      },
      {
        id: 'free-trial',
        text: 'Demander un échantillon gratuit pour « tester »',
        verdict: 'risky',
        consequenceTitle: 'Ils envoient un échantillon À VOTRE NOM. Impressionnant !',
        consequence: 'Les échantillons ne coûtent rien et ne prouvent rien — tout le monde sait mettre en page un PDF. Impressionnés, la plupart paient juste après l’échantillon.',
        feedback: 'Les échantillons prouvent le graphisme, pas l’accréditation. Jugez les émetteurs, pas les PDF.',
      },
    ],
    redFlags: [
      { label: 'Diplôme sans effort', explanation: 'Les vrais diplômes exigent apprentissage et évaluation. « 48 h, sans examens » est l’aveu.' },
      { label: 'Auto-vérification', explanation: '« Vérifiez sur notre site » signifie qu’ils contrôlent la réponse.' },
      { label: 'Inscription MoMo', explanation: 'Les institutions sérieuses utilisent admissions et reçus traçables, pas des paiements par chat.' },
    ],
    protect: ['Choisissez des programmes accrédités aux anciens vérifiables.', 'Vérifiez les émetteurs indépendamment de leur marketing.', 'Ne payez jamais de frais scolaires à des numéros personnels sous pression.'],
    xpReward: 50,
  },
  'sc-sextortion': {
    id: 'sc-sextortion',
    slug: 'sextortion-pressure',
    title: 'Menaces sur des photos privées',
    category: 'Social engineering',
    channel: 'Messages Instagram',
    sender: 'Compte avec qui vous flirtiez depuis deux semaines (jamais vu en vidéo)',
    message: '« J’ai tes photos. Envoie 30 000 FCFA dans les 3 heures ou j’envoie tout à tes abonnés, ta page d’école et ta famille. Ne me bloque pas — j’ai des comptes de secours. Dis à personne ou je publie aussitôt. »',
    contextNotes: ['Vous avez peur, honte, et vous êtes seul. C’est exactement l’état fabriqué.'],
    thinkPrompt: 'Payer semble arrêter le problème. Qui gagne si vous payez — et qu’est-ce qui l’empêche de recommencer la semaine prochaine ?',
    choices: [
      {
        id: 'pay-hide',
        text: 'Payer en silence et ne rien dire',
        verdict: 'unsafe',
        consequenceTitle: 'Payé. Trois jours plus tard : « Il m’en faut plus. »',
        consequence: 'Payer prouve que vous payez ET que le secret tient. Les demandes se répètent et grandissent — c’est le schéma documenté de presque tous les cas. Payer n’achète jamais la suppression ; ça achète un abonnement à la peur.',
        feedback: 'Ne payez jamais, ne cachez jamais. Le secret est l’infrastructure de l’attaquant — le retirer est la défense.',
      },
      {
        id: 'evidence-adult',
        text: 'Tout sauvegarder, bloquer, signaler, et en parler à quelqu’un de confiance',
        verdict: 'safe',
        consequenceTitle: 'Captures sauvegardées, compte bloqué et signalé, adulte de confiance prévenu.',
        consequence: 'Les menaces perdent leur pouvoir dès qu’elles sont partagées : les plateformes suppriment vite les comptes d’extorsion, et la plupart des bluffeurs disparaissent après plusieurs signalements. Être visé n’a rien de honteux — la honte appartient à l’extorqueur.',
        feedback: 'Correct. Preuves + blocage + signalement + personne de confiance. Ce n’est pas votre faute, et signaler vite limite les récidives.',
      },
      {
        id: 'argue-plead',
        text: 'Le supplier de supprimer et promettre n’importe quoi',
        verdict: 'risky',
        consequenceTitle: 'Supplier marche — un jour.',
        consequence: 'La pitié n’est qu’un autre levier. Chaque message leur apprend quelles menaces vous font bouger le plus vite, et le prix revient plus haut.',
        feedback: 'Négocier avec des extorqueurs les entraîne sur vous. Coupez court via la chaîne sûre.',
      },
    ],
    redFlags: [
      { label: 'Compte à rebours + secret', explanation: 'Délais de quelques heures plus « dis à personne » vous isolent de l’aide.' },
      { label: 'Menaces sur votre cercle', explanation: 'Abonnés, école, famille nommés explicitement — pression de honte maximale.' },
      { label: '« Ne me bloque pas »', explanation: 'Les consignes qui empêchent vos défenses sont elles-mêmes l’indice.' },
    ],
    protect: ['Ne payez jamais une extorsion — ça garantit les récidives.', 'Capturez tout avant de bloquer (preuves d’abord).', 'Signalez à la plateforme ; parlez-en aussitôt à un adulte de confiance.', 'Si vous êtes mineur, un adulte doit être impliqué — vous n’affrontez pas ça seul.'],
    xpReward: 60,
  },
  'sc-wrong-transfer': {
    id: 'sc-wrong-transfer',
    slug: 'wrong-transfer-refund',
    title: '« Erreur de transfert — renvoyez »',
    category: 'Everyday scams',
    channel: 'SMS + appel',
    sender: 'SMS : « Vous avez reçu 40 000 FCFA. » Puis un appel urgent d’un inconnu',
    message: 'Appelant, affolé : « Svp, j’ai envoyé 40 000 par erreur sur votre numéro — c’était mon loyer ! Je vous envoie 5 000 pour votre gentillesse, retransférez juste les 40 000 sur ce numéro, mon bailleur attend. »',
    thinkPrompt: 'La gentillesse dit rembourser. La prudence demande : l’argent est-il vraiment arrivé — et vers quel numéro doit-il repartir ?',
    choices: [
      {
        id: 'send-back',
        text: 'Renvoyer 40 000 sur leur numéro aussitôt',
        verdict: 'unsafe',
        consequenceTitle: 'Envoyé. Votre vrai solde baisse de 40 000.',
        consequence: 'Aucun transfert n’était jamais arrivé — le SMS était faux et le vrai vol, c’est VOTRE transfert sortant. Pire : si de l’argent ÉTAIT arrivé, l’envoyer vers UN AUTRE numéro (sans annulation officielle) peut blanchir des fonds volés via vous.',
        feedback: 'Deux règles : vérifiez la réception dans votre appli d’abord, et les remboursements passent par annulation officielle — jamais un nouveau transfert vers leur numéro.',
      },
      {
        id: 'official-reverse',
        text: 'Vérifier le solde ; si fonds vraiment reçus, annuler via la procédure officielle',
        verdict: 'safe',
        consequenceTitle: 'Solde vérifié : rien reçu. Affaire classée.',
        consequence: 'Dans le cas courant il n’y a aucun argent. Dans le rare cas d’erreur réelle, opérateurs et applis ont des procédures d’annulation qui protègent les deux parties. Vous utilisez celles-là — jamais de transferts manuels.',
        feedback: 'Correct. Votre solde est la vérité ; l’annulation officielle est la seule voie de remboursement.',
      },
      {
        id: 'keep-it',
        text: 'Garder — son erreur, ma chance (si l’argent est arrivé)',
        verdict: 'risky',
        consequenceTitle: 'Dépenser de l’argent qui n’est pas à vous crée ses propres ennuis.',
        consequence: 'Les vrais transferts erronés peuvent être annulés par les opérateurs, et les dépenser d’abord vous rend débiteur. La gentillesse a un canal sûr : la procédure officielle.',
        feedback: 'Ne dépensez jamais d’argent inattendu. Signalez-le et laissez la procédure officielle agir.',
      },
    ],
    redFlags: [
      { label: 'Histoire émouvante, appel urgent', explanation: 'Loyer, bailleur qui attend — conçu pour court-circuiter la vérification du solde.' },
      { label: 'Remboursement VERS LEUR numéro', explanation: 'Les annulations légitimes passent par l’opérateur/l’appli, jamais des transferts manuels.' },
      { label: 'Réception non vérifiée', explanation: 'Les SMS se falsifient. Seul le solde de votre appli compte.' },
    ],
    protect: ['Vérifiez toujours votre solde avant de croire les messages de réception.', 'N’annulez les erreurs que via les canaux officiels.', 'N’envoyez jamais de « remboursements » aux numéros d’inconnus.'],
    xpReward: 50,
  },
  'sc-fake-confirmation': {
    id: 'sc-fake-confirmation',
    slug: 'fake-payment-confirmation',
    title: 'Client « a payé » — capture à l’appui',
    category: 'Everyday scams',
    channel: 'WhatsApp (vendeur / petit commerce)',
    sender: 'Nouveau client commandant pour 85 000 FCFA en « livraison urgente »',
    message: '« J’ai envoyé l’argent ! Voici la capture de confirmation. Remettez la marchandise à mon conducteur qui attend dehors — vite, il facture à la minute ! » [La capture montre un virement avec votre nom.]',
    thinkPrompt: 'Une capture AVEC votre nom et un livreur pressé. Que prouve un paiement mieux que toute image ?',
    choices: [
      {
        id: 'release',
        text: 'Remettre la marchandise — la capture montre mon nom',
        verdict: 'unsafe',
        consequenceTitle: 'Livreur parti avec 85 000 FCFA de stock.',
        consequence: 'La capture était retouchée en minutes — noms, montants et références se falsifient trivialement. Aucun argent n’a bougé. Le « livreur pressé » existait pour empêcher la vérification.',
        feedback: 'Les captures ne prouvent rien. Seuls votre solde ou la notification officielle du marchand confirment un paiement.',
      },
      {
        id: 'verify-balance',
        text: 'Vérifier d’abord sur mon compte ; la marchandise bouge après confirmation',
        verdict: 'safe',
        consequenceTitle: 'Solde : aucun transfert reçu. Le livreur « reçoit un autre appel » et part.',
        consequence: 'Votre règle — l’argent confirmé sur MON compte avant que la marchandise bouge — coûte trente secondes et sauve votre stock. Les vrais clients attendent ; les arnaqueurs s’évaporent.',
        feedback: 'Correct. « Marchandise contre solde confirmé, jamais contre captures » est toute la politique. Affichez-la à votre étal.',
      },
      {
        id: 'half-release',
        text: 'Remettre la moitié par bonne foi',
        verdict: 'risky',
        consequenceTitle: 'La moitié du stock partie — et le « virement » n’arrive toujours pas.',
        consequence: 'Une remise partielle reste une perte, et apprend à l’arnaqueur que vous négociez sous pression. Il reviendra avec une plus grosse commande.',
        feedback: 'Pas de remises partielles sur paiements non vérifiés. Tout ou rien, confirmé d’abord.',
      },
    ],
    redFlags: [
      { label: 'Capture comme preuve', explanation: 'Les captures de paiement sont les preuves les plus faciles à falsifier.' },
      { label: 'Urgence du livreur', explanation: 'Un tiers qui attend fabrique la précipitation qui saute la vérification.' },
      { label: 'Grosse commande d’un inconnu', explanation: 'Les grosses premières commandes d’inconnus méritent les contrôles les plus stricts.' },
    ],
    protect: ['Confirmez chaque paiement sur votre compte avant de remettre la marchandise.', 'Rendez la règle publique : « Pas de remise sans solde confirmé. »', 'Méfiez-vous des urgences de livreurs, agents ou « offres limitées ».'],
    xpReward: 50,
  },
  'sc-celebrity-video': {
    id: 'sc-celebrity-video',
    slug: 'celebrity-crypto-video',
    title: 'Un célèbre double vos cryptos (vidéo)',
    category: 'Social engineering',
    channel: 'Vidéo Facebook + lien',
    sender: 'Vidéo virale : un musicien célèbre, dans son studio, face caméra',
    message: '[Vidéo, 0:47] Le musicien cite la promo exacte : « Envoyez n’importe quel montant à cette adresse dans les 2 heures et mon équipe renvoie le double. Je fais ça pour mes vrais fans. » Des milliers de likes et de commentaires « Reçu le mien, merci boss ! » La page porte son nom avec 900 000 abonnés.',
    thinkPrompt: 'Tout ce que vous voyez et entendez semble vrai. Que peut générer l’IA désormais — et que ne peut-elle jamais générer ?',
    choices: [
      {
        id: 'send-crypto',
        text: 'Envoyer un petit montant pour tester',
        verdict: 'unsafe',
        consequenceTitle: 'Envoyé. Le « test » disparaît ; la page en demande plus.',
        consequence: 'Échange de visage + clonage vocal construits depuis des interviews ; les likes et « reçu ! » sont des bots. Les transferts crypto sont irréversibles — il n’y a pas de montant de test, seulement un premier paiement.',
        feedback: 'La vidéo n’est plus une preuve. L’IA peut porter n’importe quel visage et voix. La promesse de doublement était toujours l’aveu.',
      },
      {
        id: 'check-real',
        text: 'Vérifier ses comptes certifiés et canaux officiels',
        verdict: 'safe',
        consequenceTitle: 'Vrai compte : aucun jeu. Un post épinglé alerte sur les faux.',
        consequence: 'La page virale a trois semaines avec un nom sosie ; ses vrais canaux ne parlent jamais de crypto. Vous signalez la page — les « gagnants » en commentaires faisaient partie du décor.',
        feedback: 'Correct. La vérification bat les yeux : canaux officiels, âge du compte, et la règle que les lots n’exigent jamais de paiements.',
      },
      {
        id: 'wait-see',
        text: 'Attendre et regarder les commentaires pour voir si ça paie',
        verdict: 'risky',
        consequenceTitle: 'Encore plus de « reçu ! » chaque heure.',
        consequence: 'La preuve sociale est fabriquée : les commentaires bots ne coûtent rien et arrivent à horaire. Attendre ne vérifie pas — ça laisse juste monter la pression du délai.',
        feedback: 'Les commentaires ne sont pas des preuves. Seules les sources officielles comptent.',
      },
    ],
    redFlags: [
      { label: 'Promesse de doublement', explanation: 'Aucune célébrité ne double des cryptos pour ses fans. L’économie ne tient jamais.' },
      { label: 'Délai de 2 heures', explanation: 'L’urgence bloque la seule vérification qui tue l’affaire.' },
      { label: 'Page sosie + fausses preuves', explanation: 'Jeune page, nom quasi identique, et des commentaires qui ne font que louer.' },
    ],
    protect: ['Traitez les vidéos virales comme du texte : vérifiez sur canaux officiels.', 'N’envoyez jamais de crypto aux schémas de « doublement » — l’irréversibilité est le piège.', 'Signalez les pages usurpatrices au lieu d’interagir.'],
    xpReward: 60,
  },
  'sc-ai-news-photo': {
    id: 'sc-ai-news-photo',
    slug: 'ai-disaster-photo',
    title: 'Photo choc de « dernière minute »',
    category: 'Social engineering',
    channel: 'Message WhatsApp transféré',
    sender: 'Transféré de nombreuses fois : photo d’une rue de marché inondée avec des barques de secours',
    message: '« DERNIÈRE MINUTE : marché Mokolo sous les eaux MAINTENANT. Le gouvernement le cache ! Transférez à tout le monde avant suppression !! Donnez aux victimes ici : [numéro mobile money]. » Les reflets de l’eau semblent bizarres si on regarde bien.',
    thinkPrompt: 'Panique plus charité plus « transférez avant suppression ». Que confirmerait une catastrophe pareille en deux minutes ?',
    choices: [
      {
        id: 'forward-donate',
        text: 'Transférer largement et donner quelque chose',
        verdict: 'unsafe',
        consequenceTitle: 'Transféré à 4 groupes. 5 000 FCFA donnés.',
        consequence: 'La photo était générée par IA (reflets faux, pancartes déformées, secouriste à six doigts). Aucune inondation n’existe. Votre don est parti vers un numéro personnel, et vos transferts ont offert le mensonge à 400 nouvelles victimes qui VOUS font confiance.',
        feedback: 'Transférer, c’est publier. Catastrophe + secret + dons est une formule éprouvée — vérifiez avec radio, officiels ou gens sur place d’abord.',
      },
      {
        id: 'verify-first',
        text: 'Vérifier via radio, officiels ou quelqu’un sur place avant tout',
        verdict: 'safe',
        consequenceTitle: 'Radio : jour de marché normal. Rien sur aucun canal officiel.',
        consequence: 'Deux minutes de vérification tuent un mensonge visant des milliers. Vous répondez à l’expéditeur en privé : « Cette photo est fausse — arrête de la transférer », et signalez le numéro de don.',
        feedback: 'Correct. Les grandes affirmations exigent de grandes confirmations : sources en direct plutôt que pixels transférés. Et les vraies collectes ne passent jamais par des numéros personnels viraux.',
      },
      {
        id: 'wait-quiet',
        text: 'Ne rien faire — pas mes affaires',
        verdict: 'risky',
        consequenceTitle: 'Le message circule dans vos groupes toute la journée.',
        consequence: 'Le silence le laisse courir. Plus tard, des proches paniquent et envoient de l’argent. Une petite correction privée (« vérifié, c’est faux ») ne coûte rien et brise les chaînes.',
        feedback: 'Ne pas transférer, c’est bien ; corriger discrètement, c’est mieux. Les témoins actifs brisent les chaînes.',
      },
    ],
    redFlags: [
      { label: '« Transférez avant suppression »', explanation: 'Instruction de viralité + cadrage complotiste — distribution intégrée au message.' },
      { label: 'Dons vers un numéro personnel', explanation: 'Les vrais secours passent par des organisations connues, jamais des numéros MoMo viraux.' },
      { label: 'Artefacts IA', explanation: 'Textes déformés, reflets faux, mains étranges — les indices, quand on ralentit.' },
      { label: 'Aucune confirmation en direct', explanation: 'Une vraie catastrophe de cette taille serait à la radio et chez vos proches.' },
    ],
    protect: ['Vérifiez les infos choquantes avec des sources en direct avant tout transfert.', 'Ne donnez jamais via des numéros personnels viraux.', 'Corrigez la désinfo en privé — calmement, avec la vérification faite.'],
    xpReward: 50,
  },
  'sc-deepfake-voice': {
    id: 'sc-deepfake-voice',
    slug: 'deepfake-voice-note',
    title: '« Papa » envoie un message vocal',
    category: 'Social engineering',
    channel: 'Note vocale WhatsApp',
    sender: 'Papa (voix exactement comme lui — stressée, pressée)',
    message: '[Note vocale, 0:19] « Fiston, c’est Papa. J’ai eu un accident, mon téléphone est cassé, c’est le numéro d’un ami. Il me faut 75 000 FCFA pour la clinique TOUT DE SUITE sinon ils ne vont pas me soigner. N’appelle pas maman, elle va paniquer. Envoie sur ce numéro MoMo. »',
    thinkPrompt: 'Ça ressemble exactement à lui. Que peut faire l’IA avec 30 secondes de la voix de quelqu’un — et que prouve encore l’identité ?',
    choices: [
      {
        id: 'send-now',
        text: 'Envoyer l’argent — c’est clairement sa voix',
        verdict: 'unsafe',
        consequenceTitle: 'Envoyé. Papa appelle une heure plus tard, perplexe, depuis son numéro normal.',
        consequence: 'Il était chez lui depuis le début. Le clonage vocal n’a besoin que de secondes d’audio — vidéos d’anniversaire, TikToks, statuts. La voix était parfaite parce qu’elle était construite À PARTIR de lui, pas PAR lui.',
        feedback: 'Une voix familière ne prouve plus l’identité. Les voix clonées portent le bon accent, le bon surnom, la bonne panique — la vérification doit venir d’ailleurs.',
      },
      {
        id: 'codeword',
        text: 'Demander le mot de code familial, puis appeler son vrai numéro en vidéo',
        verdict: 'safe',
        consequenceTitle: 'Aucun mot de code ne vient. Les excuses commencent.',
        consequence: '« Pas le temps pour les jeux ! » — la pression remplace la preuve. Vous appelez le vrai numéro de papa en vidéo : il répond depuis le canapé. Le mot de code familial (convenu il y a des mois « en cas d’urgence ») vient de prouver son utilité.',
        feedback: 'Correct. Mots de code convenus + vidéo en direct sur un numéro CONNU battent les clones vocaux. La pression pour sauter la vérification EST la confirmation.',
      },
      {
        id: 'half-ask',
        text: 'Envoyer un peu d’abord en essayant de le joindre',
        verdict: 'risky',
        consequenceTitle: '« La clinique dit que ça ne suffit pas, complète maintenant. »',
        consequence: 'Un paiement partiel prouve que vous payez sous pression — le script continue simplement. Et personne n’a rien vérifié.',
        feedback: 'Tout montant envoyé sur une voix non vérifiée est perdu. Vérifiez d’abord, toujours entièrement, jamais par tranches.',
      },
    ],
    redFlags: [
      { label: 'Voix parfaite, numéro inconnu', explanation: 'Le clonage explique le paradoxe : sa voix, pas son téléphone.' },
      { label: 'Secret + urgence', explanation: '« N’appelle pas maman » écarte le vérificateur ; « TOUT DE SUITE » écarte la réflexion.' },
      { label: 'Argent vers un tiers', explanation: 'Les vraies urgences passent par des personnes et numéros connus.' },
    ],
    protect: ['Convenez d’un mot de code familial pour les urgences — aujourd’hui, pas pendant.', 'Vérifiez les notes vocales choquantes en vidéo sur un numéro connu.', 'Rappelez-vous : voix, photos et vidéos peuvent désormais être générées.'],
    xpReward: 60,
  },
};
