// Scenario engine content, part 2: jobs, school, web, and account threats.

import type { Scenario } from './scenarios';

export const scenarios2: Scenario[] = [
  {
    id: 'sc-hr-fee',
    slug: 'hr-processing-fee-job',
    title: 'HR asks for a processing fee',
    category: 'Job scams',
    channel: 'Telegram',
    sender: '"Sarah, HR Manager" at a logistics company (joined Telegram last month)',
    message: 'Congratulations! You passed screening for the Data Entry role: 150,000 FCFA/month, remote, no interview needed. To process your employment file, send 10,000 FCFA to this MoMo number today. Slots close tonight.',
    thinkPrompt: 'A salary, no interview, and YOU pay THEM — tonight. Which direction does money flow in real hiring?',
    choices: [
      {
        id: 'pay',
        text: 'Pay the 10,000 FCFA — the salary is worth it',
        verdict: 'unsafe',
        consequenceTitle: 'Paid. "Next: 15,000 for the medical certificate."',
        consequence: 'Then a uniform fee, a training fee... each step small enough to feel recoverable, until 60,000 FCFA is gone and "Sarah" deletes her account. Real employers never charge to hire you.',
        feedback: 'Fees-to-be-hired is the entire scam. Money flows employer-to-you, never the reverse.',
      },
      {
        id: 'verify',
        text: 'Ask for a contract and verify the company independently',
        verdict: 'safe',
        consequenceTitle: 'The company\'s real site lists no such role — and warns about Telegram scammers.',
        consequence: 'You find their official careers page and a scam warning using the same script. You report the account and keep your 10,000.',
        feedback: 'Correct. Real hiring survives verification: official site, public phone number, written contract.',
      },
      {
        id: 'id-first',
        text: 'Send my ID and diploma first to "hold the slot", decide on fees later',
        verdict: 'risky',
        consequenceTitle: 'Slot "held". Now the fee demand arrives anyway.',
        consequence: 'Worse: they now hold your ID photo and diploma, usable for identity fraud and for scamming others in YOUR name. The fee was never the only harvest.',
        feedback: 'Documents first is also a loss. ID + diploma enable identity theft even if you never pay.',
      },
    ],
    redFlags: [
      { label: 'No interview, instant hire', explanation: 'Nobody pays 150k/month without meeting you.' },
      { label: 'Fee to be hired', explanation: 'Processing, medical, uniform fees from candidates = scam pattern.' },
      { label: 'Tonight deadline', explanation: 'Artificial scarcity blocks the verification that kills the deal.' },
      { label: 'Telegram-only HR', explanation: 'New account, no company email, no verifiable identity.' },
    ],
    protect: ['Never pay to get hired — for fees, certificates, or "files".', 'Verify roles on official company sites and public numbers.', 'Never send ID documents over chat to unverified recruiters.'],
    xpReward: 50,
  },
  {
    id: 'sc-exam-portal',
    slug: 'exam-results-portal',
    title: 'Check your exam results here',
    category: 'Student scams',
    channel: 'WhatsApp class group',
    sender: 'Forwarded many times: "OFFICIAL results portal — check before it closes!"',
    message: 'GCE / BAC results are out! Enter your candidate number AND your school email password to view your grades before the portal closes: results-check-2026.com',
    thinkPrompt: 'Results excitement plus a password field. When has your school EVER needed your email password to show grades?',
    choices: [
      {
        id: 'enter',
        text: 'Enter my candidate number and email password',
        verdict: 'unsafe',
        consequenceTitle: 'The page spins... then shows an error. "Try again later."',
        consequence: 'Your school email password is harvested. That inbox resets everything else: social accounts, MoMo PIN resets, even school portals. Days later classmates get scams "from you".',
        feedback: 'No results portal needs your EMAIL password. Candidate number alone suffices on real portals — passwords are the harvest.',
      },
      {
        id: 'school-site',
        text: 'Go to the school/exam board site myself',
        verdict: 'safe',
        consequenceTitle: 'Official board site: "Results publish Friday."',
        consequence: 'Results are not even out — the forwarded portal was pure fiction. You warn the group with a screenshot (link removed) and the admin deletes the message.',
        feedback: 'Correct. Official boards announce dates publicly. "Before it closes" is fiction designed to beat the announcement.',
      },
      {
        id: 'friend-pass',
        text: 'Ask a friend who already "checked" for their login to borrow',
        verdict: 'risky',
        consequenceTitle: 'Your friend shares her password so you can "see how it looks".',
        consequence: 'Now two accounts are compromised, and you normalized password-sharing in your class. The portal was fake for both of you.',
        feedback: 'Borrowed passwords double the damage and teach a dangerous habit. Verify the portal, not the login.',
      },
    ],
    redFlags: [
      { label: 'Password for grades', explanation: 'Real portals need candidate numbers, not email passwords.' },
      { label: 'Forwarded frenzy', explanation: '"Forwarded many times" + closing soon = manufactured stampede.' },
      { label: 'Off-domain portal', explanation: 'results-check-2026.com is not your exam board\'s domain.' },
    ],
    protect: ['Use only the exam board\'s official site, found via search or school notice.', 'Never enter email passwords on third-party pages.', 'Warn groups with screenshots, never by forwarding the link.'],
    xpReward: 50,
  },
  {
    id: 'sc-internship',
    slug: 'paid-internship-abroad',
    title: 'Paid internship abroad',
    category: 'Job scams',
    channel: 'LinkedIn DM',
    sender: 'Recruiter with a polished profile (500+ connections, stock-photo office banner)',
    message: 'Your profile is impressive! We offer a paid 3-month internship in Dubai: flights + 300,000 FCFA/month stipend. Just complete the visa processing (45,000 FCFA) through our accredited agent this week.',
    thinkPrompt: 'Prestige, travel, stipend — and one payment through "their" agent. What would a real multinational do differently?',
    choices: [
      {
        id: 'agent',
        text: 'Pay the agent — Dubai opportunity of a lifetime',
        verdict: 'unsafe',
        consequenceTitle: 'Receipt received. Then: "embassy fee", "insurance fee"...',
        consequence: 'Each fee unlocks a bigger one until you are 150,000 FCFA down and the recruiter\'s profile vanishes. LinkedIn connections can be bought; offices can be stock photos.',
        feedback: 'Real employers use official visa channels and never route payments through private agents on deadline.',
      },
      {
        id: 'verify-co',
        text: 'Verify the company, role, and agent independently',
        verdict: 'safe',
        consequenceTitle: 'The real company replies: "We have no such program."',
        consequence: 'One email to their public contact address exposes the whole thing. The fake profile gets reported, and your savings stay yours.',
        feedback: 'Correct. Verify all three: company (official site), role (official posting), agent (embassy/official lists).',
      },
      {
        id: 'passport',
        text: 'Send passport copy to "reserve" while I think about fees',
        verdict: 'risky',
        consequenceTitle: '"Reserved!" Now the pressure to pay doubles.',
        consequence: 'Your passport biodata now circulates: identity fraud, fake accounts in your name, and leverage ("we have your documents, pay or else").',
        feedback: 'Passport copies are gold for criminals. Never send them to unverified contacts for any reason.',
      },
    ],
    redFlags: [
      { label: 'Upfront visa/agent fees', explanation: 'Legitimate programs deduct costs from stipends or use official channels.' },
      { label: 'Unsolicited prestige offer', explanation: 'Out-of-nowhere Dubai internships target ambition, not qualifications.' },
      { label: 'Polished but hollow profile', explanation: 'Connections and banners are cheap; verifiable employment history is not.' },
    ],
    protect: ['Verify via official company contact — never the recruiter\'s links.', 'Never pay agents for employment visas on chat deadlines.', 'Guard passport and ID copies like cash.'],
    xpReward: 50,
  },
  {
    id: 'sc-password-reuse',
    slug: 'one-password-everywhere',
    title: 'One password everywhere',
    category: 'Account security',
    channel: 'Narrated situation (your own habit)',
    sender: 'You, being efficient',
    message: 'You use "Lionel1999!" for email, Facebook, MoMo, school portal, and betting sites. One day a small forum you joined in 2022 gets breached. Your email + password appear in a leaked list circulating on Telegram.',
    thinkPrompt: 'Nothing "important" was hacked — just an old forum. So why might this be the most dangerous scenario here?',
    choices: [
      {
        id: 'nothing',
        text: 'Ignore it — that forum means nothing to me',
        verdict: 'unsafe',
        consequenceTitle: 'Weeks later: password-reset emails you did not request.',
        consequence: 'Credential stuffing: attackers replayed your leaked pair against email, Facebook, and MoMo. Same password everywhere means one leak opens every door. Recovery takes weeks; some money does not come back.',
        feedback: 'Breaches are normal now. The question is never IF a password leaks — it is whether it opens anything else.',
      },
      {
        id: 'change-all',
        text: 'Change that password everywhere and switch on MFA',
        verdict: 'safe',
        consequenceTitle: 'New unique passwords via a password manager + MFA on email first.',
        consequence: 'The leaked password becomes a dead key. Attackers try it across fifty sites and it fits nothing. Total damage: zero.',
        feedback: 'Correct. Unique passwords contain breaches; MFA on email first protects the master key to everything else.',
      },
      {
        id: 'tweak',
        text: 'Add "123" to the end everywhere — good enough',
        verdict: 'risky',
        consequenceTitle: '"Lionel1999!123" everywhere. Attackers try variations automatically.',
        consequence: 'Credential-stuffing tools mutate passwords (add digits, capitalize) by default. Predictable tweaks fall in minutes.',
        feedback: 'Human-predictable changes are machine-guessable. Unique random passwords per site is the actual fix.',
      },
    ],
    redFlags: [
      { label: 'Reused credential', explanation: 'One leak = every account, when passwords match.' },
      { label: 'No MFA', explanation: 'Without a second factor, a password alone is total access.' },
      { label: 'Old forgotten accounts', explanation: 'Forums you forgot still hold the key you reuse.' },
    ],
    protect: ['Use a password manager: one unique random password per site.', 'Enable MFA on email first, then bank, MoMo, and social accounts.', 'When a breach hits, change that password everywhere it was reused.'],
    xpReward: 40,
  },
  {
    id: 'sc-giveaway',
    slug: 'influencer-giveaway-fee',
    title: 'Influencer giveaway (pay shipping)',
    category: 'Everyday scams',
    channel: 'Instagram',
    sender: 'Account with an influencer\'s photos, 800 followers, "GIVEAWAY ends tonight"',
    message: 'CONGRATS! You won the iPhone 15 giveaway. Pay 5,000 FCFA delivery fee via MoMo to this number within 2 hours to receive your prize.',
    thinkPrompt: 'You won something you never entered, from an account with 800 followers, and the prize needs YOUR payment. Count the red flags.',
    choices: [
      {
        id: 'pay-ship',
        text: 'Pay the 5,000 FCFA shipping — iPhones cost far more',
        verdict: 'unsafe',
        consequenceTitle: 'Paid. "Customs fee next: 12,000 FCFA."',
        consequence: 'The iPhone never existed. The fee ladder continues until you stop — every step "small compared to an iPhone". The account blocks you after the third payment.',
        feedback: 'Prizes never require winner payments. "Shipping/customs/verification" fees on winnings are advance-fee scams.',
      },
      {
        id: 'check-real',
        text: 'Check the influencer\'s real verified account',
        verdict: 'safe',
        consequenceTitle: 'Real account (2M followers): no giveaway, plus a scam warning.',
        consequence: 'The real influencer posted last month: "Fake accounts are running giveaways in my name." You report the impersonator in two taps.',
        feedback: 'Correct. Follower counts, verification badges, and the real account\'s own posts expose impersonators instantly.',
      },
      {
        id: 'tag-friend',
        text: 'Tag friends so they can win too',
        verdict: 'risky',
        consequenceTitle: 'Three friends "win" within the hour.',
        consequence: 'Tagging recruits victims for the scammer and spends your credibility. Your friends lose money because you vouched with a tag.',
        feedback: 'Never amplify unverified giveaways. Tags are endorsements — verify before spending them.',
      },
    ],
    redFlags: [
      { label: 'Won without entering', explanation: 'Unsolicited winnings are always fake.' },
      { label: 'Fee to receive', explanation: 'Real prizes deduct costs or are free — never MoMo-to-a-number.' },
      { label: 'Impersonator account', explanation: 'Stolen photos, low followers, urgency bio.' },
      { label: '2-hour deadline', explanation: 'Speed prevents the one check that kills the scam.' },
    ],
    protect: ['Verify giveaways on the real verified account.', 'Never pay fees to receive prizes.', 'Report impersonators instead of tagging friends.'],
    xpReward: 40,
  },
  {
    id: 'sc-qr-menu',
    slug: 'qr-menu-sticker',
    title: 'QR menu with a sticker over it',
    category: 'Safe browsing',
    channel: 'In person (restaurant)',
    sender: 'Table QR code with a slightly crooked sticker pasted over the original',
    message: 'You scan it. Your browser opens "menu-restaurant-pay.com" asking you to "log in with Google to view the menu and pay from your table".',
    thinkPrompt: 'A menu that needs your Google login. What does viewing food prices have to do with your Google account?',
    choices: [
      {
        id: 'login-pay',
        text: 'Log in with Google and pay — it is convenient',
        verdict: 'unsafe',
        consequenceTitle: 'Logged in. The menu even works!',
        consequence: 'The sticker was a quishing overlay. Your Google credentials went to the attacker, who now owns your email — and through it, password resets for everything. The working menu was the camouflage.',
        feedback: 'Menus never need Google logins. Stickers over QR codes are a known attack (quishing) — the overlay leads to credential harvest.',
      },
      {
        id: 'ask-staff',
        text: 'Ask staff for the real menu and check the URL',
        verdict: 'safe',
        consequenceTitle: 'Staff peel off the sticker: different URL underneath.',
        consequence: 'The real QR was replaced that morning. Staff remove all stickers, you order normally, and the attacker gets nothing from your table.',
        feedback: 'Correct. Verify physical codes like digital ones: compare with staff, preview URLs before entering anything.',
      },
      {
        id: 'photo-later',
        text: 'Take a photo of the QR and scan it at home on Wi-Fi',
        verdict: 'risky',
        consequenceTitle: 'At home, same fake page, same login prompt.',
        consequence: 'Location never mattered — the destination was malicious wherever you open it. Delaying does not disinfect a bad link.',
        feedback: 'A malicious destination is malicious everywhere. Verify the SOURCE, not the network.',
      },
    ],
    redFlags: [
      { label: 'Tampered code', explanation: 'Crooked sticker over the original = replaced destination.' },
      { label: 'Login for a menu', explanation: 'No legitimate menu needs your Google account.' },
      { label: 'Lookalike pay-domain', explanation: 'menu-restaurant-pay.com is not the restaurant\'s site.' },
    ],
    protect: ['Inspect QR codes for stickers/overlays; confirm with staff.', 'Preview URLs before opening; never log in from random QRs.', 'Type payment addresses yourself.'],
    xpReward: 40,
  },
  {
    id: 'sc-attachment-invoice',
    slug: 'invoice-attachment-email',
    title: 'Overdue invoice attachment',
    category: 'Email threats',
    channel: 'Email',
    sender: '"Billing Dept" <billing@acme-corp-invoices.com>',
    message: 'Subject: Invoice #INV-0451 OVERDUE — service suspension in 24h. "See attached invoice and remit payment to avoid interruption." Attachment: Invoice-0451.html (47 KB). You have never heard of Acme Corp.',
    thinkPrompt: 'An invoice from a company you never used, with an HTML attachment and a 24-hour threat. What is the attachment FOR?',
    choices: [
      {
        id: 'open',
        text: 'Open the attachment to see what I supposedly owe',
        verdict: 'unsafe',
        consequenceTitle: 'The "invoice" opens in your browser asking for email login "to view".',
        consequence: 'HTML attachments render fake login pages that steal credentials — and can carry malware. Curiosity about a debt you do not owe just cost real passwords.',
        feedback: 'Unexpected attachments are the payload, not information. Unknown sender + unknown debt = delete.',
      },
      {
        id: 'pay-call',
        text: 'Call the phone number in the attachment to dispute it',
        verdict: 'risky',
        consequenceTitle: 'A "billing agent" answers and offers to "verify your account".',
        consequence: 'The number belongs to the scammers. The dispute call becomes a social-engineering session harvesting your details with professional patience.',
        feedback: 'Contact details inside a scam message belong to the scam. Dispute through independently-found numbers only.',
      },
      {
        id: 'delete-report',
        text: 'Delete it and report as phishing — I owe Acme nothing',
        verdict: 'safe',
        consequenceTitle: 'Deleted, reported. Nothing owed, nothing opened.',
        consequence: 'The whole thing relied on panic over a fake debt. Your rule — no relationship, no payment, no open — ends it in ten seconds.',
        feedback: 'Correct. Unknown company + unexpected attachment + urgency = report and delete, no engagement.',
      },
    ],
    redFlags: [
      { label: 'Unknown biller', explanation: 'You cannot owe a company you never used.' },
      { label: 'HTML attachment', explanation: 'Invoices are PDFs; .html attachments open credential-harvesting pages.' },
      { label: 'Suspension threat', explanation: '24-hour threats manufacture the panic that opens attachments.' },
    ],
    protect: ['Never open unexpected attachments — especially .html, .doc with macros, .apk.', 'Verify debts through companies you actually use, via official channels.', 'Report phishing instead of disputing it with the sender.'],
    xpReward: 50,
  },
];
