// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview A cybersecurity advice generation AI agent.
 *
 * - generateCybersecurityAdvice - A function that generates cybersecurity advice.
 * - GenerateCybersecurityAdviceInput - The input type for the generateCybersecurityAdvice function.
 * - GenerateCybersecurityAdviceOutput - The return type for the generateCybersecurityAdvice function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateCybersecurityAdviceInputSchema = z.object({
  digitalHabits: z
    .string()
    .describe(
      'A detailed description of the user\u2019s digital habits, including the types of websites they visit, the apps they use, their social media activity, and any other relevant online behavior.'
    ),
  potentialVulnerabilities: z
    .string()
    .describe(
      'A list of potential cybersecurity vulnerabilities the user may have, based on their digital habits. This could include weak passwords, lack of two-factor authentication, or risky online behavior.'
    ),
});
export type GenerateCybersecurityAdviceInput = z.infer<
  typeof GenerateCybersecurityAdviceInputSchema
>;

const GenerateCybersecurityAdviceOutputSchema = z.object({
  advice: z.string().describe('Customized cybersecurity advice for the user.'),
});
export type GenerateCybersecurityAdviceOutput = z.infer<
  typeof GenerateCybersecurityAdviceOutputSchema
>;

export async function generateCybersecurityAdvice(
  input: GenerateCybersecurityAdviceInput
): Promise<GenerateCybersecurityAdviceOutput> {
  return generateCybersecurityAdviceFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateCybersecurityAdvicePrompt',
  input: {schema: GenerateCybersecurityAdviceInputSchema},
  output: {schema: GenerateCybersecurityAdviceOutputSchema},
  prompt: `You are an AI cybersecurity assistant. You will generate customized cybersecurity advice for the user, based on their digital habits and potential vulnerabilities.

Digital Habits: {{{digitalHabits}}}
Potential Vulnerabilities: {{{potentialVulnerabilities}}}

Cybersecurity Advice:`,
});

const generateCybersecurityAdviceFlow = ai.defineFlow(
  {
    name: 'generateCybersecurityAdviceFlow',
    inputSchema: GenerateCybersecurityAdviceInputSchema,
    outputSchema: GenerateCybersecurityAdviceOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
