import placeholderData from './placeholder-images.json';

const placeholderImages: { id: string; imageUrl: string; imageHint: string }[] =
  (placeholderData as any).placeholderImages ?? [];

type Article = {
  slug: string;
  title: string;
  description: string;
  category: string;
  imageUrl: string;
  imageHint: string;
  content: string;
};

const findImage = (id: string) => {
    const img = placeholderImages.find(p => p.id === id);
    return {
        imageUrl: img?.imageUrl || "https://picsum.photos/seed/default/600/400",
        imageHint: img?.imageHint || "placeholder"
    }
}

export const articles: Article[] = [
  {
    slug: 'understanding-phishing',
    title: 'How to Recognize and Avoid Phishing Scams',
    description: 'Learn the tell-tale signs of phishing emails and protect yourself from credential theft and malware.',
    category: 'Email Security',
    ...findImage('article1'),
    content: `Phishing is one of the most common forms of cyber attacks, and it's surprisingly effective. The core idea is simple: an attacker sends a fraudulent message designed to trick a human victim into revealing sensitive information or deploying malicious software. These messages often look like they're from reputable sources, like your bank, a social media site, or even a government agency.

    The first step to avoiding phishing is to be skeptical of any unsolicited email, text, or social media message, especially if it asks for personal information or urges you to act quickly. Look for red flags. Does the sender's email address look legitimate? Hover over links before clicking to see the actual destination URL. Attackers often use URLs that are similar to, but not exactly the same as, a legitimate site.

    Other signs include poor grammar and spelling, generic greetings like "Dear Customer," and a sense of urgency or threats. For example, an email might claim your account will be suspended if you don't click a link and "verify" your information immediately. Legitimate companies rarely, if ever, ask for sensitive data via email. If you're unsure, don't click the link. Instead, go directly to the company's website by typing the address into your browser or use a trusted app and check your account status there.`
  },
  {
    slug: 'creating-strong-passwords',
    title: 'The Art of Creating Strong and Memorable Passwords',
    description: 'Move beyond "Password123" and master the techniques for crafting passwords that are both secure and easy to remember.',
    category: 'Password Security',
    ...findImage('article2'),
    content: `Your passwords are the first line of defense for your digital life. A weak password is like leaving your front door unlocked. The key to a strong password is a combination of length and complexity. A good starting point is at least 12-16 characters.

    But how do you remember such a long and complex password? The answer is to use a passphrase. Instead of a single, hard-to-remember word, think of a short, memorable sentence. For example, "MyDogLoves-Green-TennisBalls!". This is long, contains uppercase and lowercase letters, a number (if you wanted to change 'one' to '1'), and a symbol. It's far more secure and easier to remember than "P@ssw0rd1!".

    The most important rule of all is to never reuse passwords across different services. If one site is breached, attackers will use your credentials to try and access your other accounts. To manage this, use a password manager. These tools generate and store strong, unique passwords for all your accounts, and you only need to remember one master password to access them. It's the single best step you can take to improve your password security.`
  },
  {
    slug: 'two-factor-authentication',
    title: 'Why You Need Two-Factor Authentication (2FA)',
    description: 'Understand what 2FA is and why it\'s one of the most effective ways to secure your online accounts.',
    category: 'Account Security',
    ...findImage('article3'),
    content: `Two-Factor Authentication, or 2FA, adds a crucial second layer of security to your online accounts. Even if an attacker steals your password, they still won't be able to log in without access to your second factor. It's like having two different locks on your front door.

    So how does it work? When you log in with your password, the service will prompt you for a second piece of information. This 'second factor' is typically something only you have access to. Common types of 2FA include a code sent to your phone via SMS, a code generated by an authenticator app (like Google Authenticator or Authy), or a physical security key (like a YubiKey).

    While any 2FA is better than none, authenticator apps and physical keys are generally more secure than SMS-based 2FA, as text messages can sometimes be intercepted. Most major online services—including Google, Apple, Facebook, and your bank—offer 2FA. Take a few minutes to enable it on all of your important accounts. It's a simple step that provides a massive boost to your personal cybersecurity.`
  },
  {
    slug: 'public-wifi-risks',
    title: 'The Hidden Dangers of Public Wi-Fi',
    description: 'Coffee shops and airports offer convenience, but their Wi-Fi networks come with risks. Learn how to stay safe.',
    category: 'Network Security',
    ...findImage('article4'),
    content: `Public Wi-Fi is incredibly convenient, but it's also a breeding ground for security risks. When you connect to an unsecured network, you have no idea who else is on it. A cybercriminal on the same network could potentially intercept the data you send and receive—a technique known as a 'Man-in-the-Middle' (MitM) attack.

    To protect yourself, the best solution is to use a Virtual Private Network (VPN). A VPN encrypts all your internet traffic, creating a secure tunnel between your device and the internet. Even if an attacker intercepts your data, it will be unreadable gibberish to them.

    If you don't have a VPN, there are still precautions you can take. First, make sure you're connecting to the legitimate Wi-Fi network for the establishment. Attackers can set up "evil twin" networks with similar names to trick you into connecting. Second, avoid accessing sensitive sites like online banking or entering passwords. Stick to browsing that doesn't involve personal information. Finally, ensure the websites you visit use HTTPS (look for the padlock icon in your browser's address bar), which encrypts the connection between your browser and the website.`
  },
  {
    slug: 'securing-your-home-wifi',
    title: 'How to Secure Your Home Wi-Fi Network',
    description: 'Your home network is the gateway to your digital life. Learn these essential steps to lock it down.',
    category: 'Network Security',
    ...findImage('article5'),
    content: `Securing your home Wi-Fi network is a critical step in protecting your personal information. An unsecured network can give attackers access to all the devices connected to it. Start by changing the default administrator username and password for your router. These are often public knowledge and provide an easy entry point.

    Next, ensure your network is using the strongest available encryption. Look for WPA3 in your router's settings. If it's not available, WPA2 is the next best choice. Avoid older standards like WPA and WEP, which are no longer secure. You should also create a strong, unique password for the Wi-Fi network itself.

    For added security, consider creating a separate "guest" network for visitors. This isolates their devices from your main network, where your sensitive devices like computers and file servers reside. Finally, disable Wi-Fi Protected Setup (WPS) if your router has it. While convenient, it has known vulnerabilities that can be exploited.`
  },
  {
    slug: 'how-to-verify-links',
    title: 'Don\'t Click Blindly: How to Verify Suspicious Links',
    description: 'Learn the techniques to inspect links before you click and avoid falling for phishing scams and malware traps.',
    category: 'Web Security',
    ...findImage('article6'),
    content: `A malicious link can lead to disastrous consequences, from credential theft to a full-blown malware infection. Learning to spot them is a crucial skill. The single most important technique is to hover your mouse over any link before you click it. Your browser will display the link's true destination in the bottom corner of the window. If the destination doesn't match the link text or seems suspicious, don't click.

    Pay close attention to the domain name. Attackers often use "typosquatting," where they register domains that are very similar to legitimate ones (e.g., 'paypa1.com' instead of 'paypal.com'). Be wary of links that use URL shorteners (like bit.ly or tinyurl.com) in unexpected contexts, as they hide the final destination. You can use a URL expander service to check where a shortened link goes without actually visiting it.

    Context is also key. Did you expect this email or message? Does it make sense for this person or company to send you this link? If you receive a message from your "bank" with a link to "verify your account," be suspicious. When in doubt, always navigate to a website directly by typing its address into your browser rather than clicking a link in an email.`
  },
  {
    slug: 'what-is-a-vpn',
    title: 'What is a VPN and Do I Really Need One?',
    description: 'Demystify Virtual Private Networks and find out when and why you should be using one to protect your privacy.',
    category: 'Privacy',
    ...findImage('article7'),
    content: `A Virtual Private Network, or VPN, is a powerful tool for enhancing your online privacy and security. It works by creating an encrypted "tunnel" for your internet traffic. This tunnel connects your device to a remote server operated by the VPN provider. From there, your traffic exits onto the public internet.

    This process has two main benefits. First, the encryption prevents anyone on your local network—like other users on a public Wi-fI hotspot or even your own Internet Service Provider (ISP)—from snooping on your activity. Second, because your traffic appears to come from the VPN server, it masks your real IP address, which helps protect your location and identity from websites you visit.

    So, do you need one? If you frequently use public Wi-Fi at coffee shops, airports, or hotels, a VPN is essential to protect you from potential snoops. It's also useful for preventing your ISP from tracking your browsing habits. While you may not need a VPN for casual browsing on your secure home network, it's an invaluable tool for anyone who values their digital privacy and security in the wider world.`
  },
  {
    slug: 'what-is-ransomware',
    title: 'Ransomware: What It Is and How to Protect Yourself',
    description: 'Learn about the growing threat of ransomware and the steps you can take to prevent your data from being held hostage.',
    category: 'Malware',
    ...findImage('article8'),
    content: `Ransomware is a type of malicious software that blocks access to a computer system or files, usually by encrypting them, until a sum of money (a "ransom") is paid. This has become one of the most widespread and damaging threats for individuals and organizations alike. The attackers demand payment, often in cryptocurrency like Bitcoin, to provide a decryption key.

    The most common way to get infected with ransomware is through phishing emails that contain malicious attachments or links to compromised websites. It can also spread through software vulnerabilities or by gaining access to a network. Once your files are encrypted, you'll typically see a message on your screen explaining the situation and providing instructions for payment.

    Prevention is the best defense against ransomware. The most critical step is to maintain regular, offline backups of your important data. If you have a clean backup, you can restore your files without paying the ransom. You should also be cautious about opening unsolicited attachments, keep your operating system and software updated to patch vulnerabilities, and use reputable security software. Enabling 'Controlled Folder Access' on Windows can also help prevent unauthorized applications from modifying your important files.`
  },
  {
    slug: 'social-engineering-explained',
    title: 'Social Engineering: The Art of Human Hacking',
    description: 'Discover how attackers manipulate psychology to trick you into divulging sensitive information or taking risky actions.',
    category: 'Human Factor',
    ...findImage('article9'),
    content: `Cybersecurity isn't just about technology; it's also about people. Social engineering is the art of manipulating, influencing, or deceiving victims in order to gain control over their computer systems. Unlike traditional hacking, social engineering targets human psychology rather than technical vulnerabilities.

    Common tactics include pretexting (creating a fabricated scenario), baiting (luring with a false promise), and quid pro quo (offering something in exchange for information). For example, an attacker might call you pretending to be from tech support and ask for your password to "fix" a non-existent problem. Or they might leave a malware-infected USB drive labeled "Confidential Salaries" in an office lobby for a curious employee to find and plug into their computer.

    The best defense against social engineering is awareness and a healthy dose of skepticism. Be wary of unsolicited requests for information, especially if they create a sense of urgency or fear. Verify the identity of anyone asking for sensitive data through a separate, trusted channel. Remember, if an offer seems too good to be true, it probably is.`
  },
  {
    slug: 'importance-of-software-updates',
    title: 'Update Now! The Critical Importance of Software Updates',
    description: 'Those update notifications might seem annoying, but they are one of your strongest defenses against cyberattacks.',
    category: 'System Security',
    ...findImage('article10'),
    content: `Software updates do more than just add new features; they are essential for your digital security. When developers discover a vulnerability in their software, they release a patch to fix it. Cybercriminals actively search for devices running outdated software so they can exploit these known vulnerabilities. Delaying updates leaves you as a sitting duck.

    This applies to everything on your device: your operating system (Windows, macOS, Android, iOS), your web browser, your applications, and even the firmware for your router. Many devices and applications offer automatic updates—you should enable this feature whenever possible. It's the easiest way to ensure you're always protected against the latest known threats.

    Don't ignore update notifications. While it might seem inconvenient to restart your computer or wait for an app to update, the few minutes it takes is a small price to pay to prevent a security breach. Make it a habit to check for updates regularly if they aren't happening automatically.`
  },
  {
    slug: 'data-backup-strategy',
    title: 'Backup or Bust: Your Last Line of Defense',
    description: 'Hardware fails and ransomware strikes. A solid backup strategy is your ultimate safety net for your digital life.',
    category: 'Data Protection',
    ...findImage('article11'),
    content: `Imagine losing all your family photos, important documents, and personal files in an instant. It can happen due to a hard drive failure, a ransomware attack, theft, or accidental deletion. A reliable backup strategy is the only thing that can save you from permanent data loss.

    The best practice is the 3-2-1 rule: Keep at least three copies of your data, store two copies on different types of media (e.g., an external hard drive and cloud storage), and keep one copy off-site. 'Off-site' means in a different physical location. If your house floods, having a backup drive sitting next to your computer won't help.

    Cloud backup services (like Backblaze, Carbonite, or even just using Google Drive/iCloud Drive) are an excellent and easy way to get an off-site backup. For local backups, you can use an external hard drive. Operating systems like Windows (File History) and macOS (Time Machine) have built-in tools that make this process simple. Set a schedule and make your backups automatic. Don't wait until it's too late.`
  },
  {
    slug: 'securing-mobile-devices',
    title: 'Your Phone is Your Life: How to Secure It',
    description: 'Smartphones are powerful computers that hold our most sensitive data. Learn the essential steps to protect your mobile device.',
    category: 'Mobile Security',
    ...findImage('article12'),
    content: `Your smartphone is a constant companion and holds a universe of personal data, from private messages and photos to banking and email access. Securing it is just as important as securing your computer. The first and simplest step is to use a strong passcode or, even better, biometric authentication like a fingerprint or facial recognition. A simple 4-digit PIN is not enough.

    Be mindful of the apps you install and the permissions you grant them. Only download apps from official app stores (Google Play Store, Apple App Store). Before an app installs, and sometimes during use, it will ask for permissions to access your contacts, location, microphone, etc. Ask yourself if the app truly needs that access to function. A simple game probably doesn't need to know your location or read your contacts.

    Just like with laptops, avoid using public Wi-Fi for sensitive tasks unless you're using a VPN. Keep your phone's operating system (iOS or Android) updated to get the latest security patches. Finally, enable "Find My" services (Find My iPhone for Apple, Find My Device for Android). This allows you to remotely locate, lock, or even erase your device if it's lost or stolen, preventing your data from falling into the wrong hands.`
  },
  {
    slug: 'digital-self-defense',
    title: 'Digital Self-Defense for Non-Techies',
    description: 'A no-panic guide to cybersecurity for people who just want to stay safe online without becoming an expert.',
    category: 'General Security',
    ...findImage('article13'),
    content: `**Part 1: The 5 "Don't Panic" Rules**

**The Password Rule of Thumb:** A simple trick is to make passwords like a bad sandwich recipe: \`PurpleElephant!Ate7Pizzas@Moon\`. If you suspect a breach, change passwords starting with email, then banking, then social media. This works because long phrases are easier to remember and much harder to crack than common substitutions like \`P@ssw0rd123\`.

**The Grandparent Text Rule:** If a text or email seems odd, ask yourself: "Would my grandma send this?" An urgent message saying "Your account is locked!" is probably fake. A link from "Amazon" where the sender's email is \`amazon-support@weirddomain.ru\` is definitely fake.

**The 2-Minute Delay Rule:** When you see something urgent, wait two minutes before reacting. If you clicked something suspicious, immediately disconnect from Wi-Fi (turn on airplane mode), run an antivirus scan, and change your password from a different device.

**The Phone Call Verification Rule:** If "your bank" calls asking for information, hang up. Call them back using the number on your actual debit or credit card. If you already gave them information, call the real company immediately to freeze your accounts.

**The App Download Checklist:** Before downloading any app, ask: Is it from the official app store? Does it have over 100,000 downloads? Do the reviews look real (not all generic 5-star ratings)?

**Part 2: "Set It and Forget It" Safety Settings**

For a great one-time setup, turn on automatic updates for your phone, computer, and apps. Enable 2-factor authentication on your three most important accounts: your primary email, your main bank account, and your primary social media or Apple/Google ID. Also, set up "Find My Phone," which allows you to wipe your data if the device is lost or stolen.

For a "good enough" backup plan, use free services like Google Photos or Apple iCloud for your photos. Once a month, copy your most important documents to a USB drive and label it clearly. Focus on backing up photos and documents. Don't save your password list in a file named "passwords.txt".

**Part 3: Spot the Scam – Real World Examples**

**"You Won a Prize!":** If you didn't enter a contest, you didn't win. A huge red flag is any request to "pay a small fee to claim your prize."

**The "Tech Support" Pop-up:** Microsoft and Apple will never contact you through a browser pop-up window. If you see one, close your browser completely. If it won't close, use Task Manager (Ctrl+Alt+Delete on Windows) or Force Quit (Cmd+Option+Esc on Mac).

**The Too-Good-to-Be-True Deal:** That $50 brand-new iPhone 14 is actually a $50 lesson in scams. Before buying from an unfamiliar website, search for "[website name] + scam" to see if others have reported issues.

**Part 4: Emergency Quick Guide**

**If you think you're hacked:** First, stop and don't click anything else. Disconnect from the internet. From a *different, trusted* device, change your passwords, starting with your email. Check your bank and credit card accounts for strange transactions. If money is involved, call your bank immediately.

**If you get ransomware ("Your files are locked!"):** Do not pay the ransom; there's no guarantee you'll get your files back. Take a photo of the ransom screen with your phone and ask for help from a local computer repair shop or a tech-savvy friend.

**If your identity might be stolen:** Freeze your credit, which is free at all three bureaus (Equifax, Experian, TransUnion). File a report at IdentityTheft.gov and notify your banks.

**Part 5: Making It Stick – For People Who Don't Care**

**The "Lazy Person's" Security:** Use a password manager—even a locked note in your phone is better than nothing, just don't label it "Passwords." If you reuse a PIN, at least make it 6 digits instead of 4. Don't do your banking on public Wi-Fi; save it for your home network.

**The "I Have Nothing to Hide" Response:** You lock your house door, right? This is the digital version of that. It's not about hiding, it's about not giving strangers your diary.

**Monthly "Security Snack" Routine:** While watching TV, use the commercial breaks. First break: check bank transactions. Second break: update one app on your phone. Third break: delete old emails you don't need.

**Part 6: Real Talk – What Actually Matters**

**Worry about THIS:** Your email password (it unlocks everything else), your phone (it's your life in your pocket), and your debit card number (credit cards have better fraud protection).

**Don't stress about THIS:** "Hackers watching through your camera" (put a sticker on it if you're worried), being perfectly secure (good enough is fine), and remembering everything (just know who to ask for help).

Find a "Security Buddy"—a friend or family member you can text about weird messages and who can help you with updates twice a year.

**Bottom Line:** You don't need to be a cybersecurity expert. You just need to be slightly more careful online than you are in a parking lot at night. Trust your gut—if something feels "off," it probably is. The goal isn't to be perfectly secure. The goal is to be enough of a pain to hack that criminals move on to someone easier. You're not building a fortress—you're putting a better lock on your door than your neighbor has.`
  },
  {
    slug: 'sim-swapping-scams',
    title: 'SIM Swapping: How Scammers Steal Your Phone Number',
    description: 'Discover the dangerous scam where criminals take over your phone number to bypass 2FA and access your accounts.',
    category: 'Mobile Security',
    ...findImage('article14'),
    content: `SIM swapping is a sophisticated and devastating attack where a scammer convinces your mobile carrier to transfer your phone number to a new SIM card they control. Once they have your number, they can intercept calls, text messages, and, most importantly, the two-factor authentication (2FA) codes sent via SMS. This allows them to reset passwords and gain access to your most sensitive accounts, like email and banking.

How do they do it? Scammers often start by gathering personal information about you from data breaches or your social media profiles. They then contact your mobile provider, impersonating you, and claim your phone was lost or damaged. They use the personal information they gathered to answer security questions and authorize the "swap."

To protect yourself, first, use non-SMS based 2FA whenever possible, such as an authenticator app or a physical security key. These methods are not vulnerable to SIM swapping. Second, contact your mobile provider and ask about adding a PIN or password to your account for extra security. This makes it harder for a scammer to make unauthorized changes. Finally, be cautious about the personal information you share online.`
  },
  {
    slug: 'understanding-digital-footprints',
    title: 'What is Your Digital Footprint and How to Clean It',
    description: 'Every click, like, and share creates a trail. Learn what your digital footprint is and the steps to manage it.',
    category: 'Privacy',
    ...findImage('article15'),
    content: `Your digital footprint is the trail of data you leave behind when you use the internet. It includes everything from the websites you visit, the emails you send, and the information you submit to online services. There are two types: active footprints, which are the data you intentionally share (like social media posts), and passive footprints, which are data collected without your knowledge (like your IP address or browsing history tracked by cookies).

A large digital footprint can expose you to risks like identity theft, targeted advertising, and even reputational damage. It's important to periodically review and manage your online presence. Start by searching your own name online to see what information is publicly available.

To clean up your footprint, begin by deleting old accounts you no longer use. Review the privacy settings on your current social media accounts and limit what you share publicly. Use privacy-focused browsers or extensions that block trackers. You can also submit requests to data broker websites to have your personal information removed. Taking control of your digital footprint is an ongoing process, but it's a vital part of modern digital hygiene.`
  },
  {
    slug: 'the-threat-of-juice-jacking',
    title: 'Juice Jacking: The Danger of Public USB Chargers',
    description: 'Plugging into a public USB port could be riskier than you think. Learn about "juice jacking" and how to charge safely.',
    category: 'Mobile Security',
    ...findImage('article16'),
    content: `Juice jacking is a cyber attack where malware is installed or data is stolen from a device using a compromised public USB charging port. These malicious ports can be found in places like airports, cafes, and hotels. When you plug your phone or tablet in, you might think you're only charging your battery, but the USB connection can also transfer data.

Attackers can modify these USB ports to act like a keyboard, allowing them to type commands on your device, or they can silently install malware that steals your passwords, credit card numbers, and other personal data. The risk is real, as it's impossible to tell if a public port has been tampered with just by looking at it.

The safest way to charge in public is to use your own AC power adapter and plug it into a standard electrical outlet. If you must use a USB port, use a "charge-only" cable that doesn't have the data wires connected. Another great tool is a "USB data blocker," a small adapter that sits between your charging cable and the port, physically blocking the data connection while still allowing power to flow through.`
  },
  {
    slug: 'anatomy-of-a-url',
    title: 'Anatomy of a URL: How to Read a Web Address',
    description: 'Go beyond just hovering. Learn to dissect a URL to spot the subtle tricks scammers use to create convincing fakes.',
    category: 'Web Security',
    ...findImage('article17'),
    content: `Understanding the structure of a URL is a superpower in the fight against phishing. Let's break down an example: \`https://my-account.secure-login.com/path/to/page\`.

The most important part is the **domain name**, which is the part immediately before the first single slash ('/'). In this case, it's \`secure-login.com\`. Everything before that, like \`my-account\`, is a **subdomain**. Scammers often put familiar names in the subdomain to trick you. For example, in \`https://paypal.com.secure-login.com\`, the real domain is still \`secure-login.com\`, not PayPal. Always read from right to left until you hit that first slash.

The very beginning of the URL is the **protocol**. \`https\` means your connection to the site is encrypted, which is good, but scammers can use HTTPS too, so it's not a guarantee of safety. Anything after the domain name is the **path**, which just directs you to a specific page on that domain. When you're checking a link, focus all your attention on the true domain name. If it doesn't match the company it claims to be from, it's a scam.`
  },
  {
    slug: 'securing-social-media-accounts',
    title: 'Lock it Down: A Guide to Securing Your Social Media',
    description: 'Your social media accounts are a treasure trove for scammers. Learn how to tighten your privacy and security settings.',
    category: 'Account Security',
    ...findImage('article18'),
    content: `Social media accounts are prime targets for hackers and data miners. They contain personal information, photos, and a network of contacts—all valuable for identity theft and social engineering. Securing these accounts is crucial.

Start by conducting a privacy checkup. Go through the privacy and security settings on each platform (Facebook, Instagram, X/Twitter, LinkedIn, etc.). Set your posts and personal information (like your birthday and phone number) to be visible to "Friends Only" instead of "Public." This prevents strangers from harvesting your data. Be mindful of what you post; avoid sharing information that could be used as answers to security questions, like your mother's maiden name or your first pet's name.

Next, enable Two-Factor Authentication (2FA) on every social media account that offers it. This is your strongest defense against takeovers. Finally, review which third-party apps are connected to your accounts. You may have granted access to quizzes or games years ago that you no longer use. Revoke access for any app you don't recognize or trust, as these can be a backdoor into your account.`
  },
  {
    slug: 'sender-check-rule',
    title: 'The "Sender Check" Rule',
    description: 'Look at the sender\'s actual address, not just their name. If it looks weird, it\'s probably fake.',
    category: 'Quick Tips',
    ...findImage('tip1'),
    content: `When you get any email/text with a link: Look at the sender's actual address, not just their name. If it's claiming to be from Netflix but coming from \`service-update@secure-netflix.xyz.ru\`, it's fake. The stuff after the last dot should make sense (.com, .org, .net, etc., not random letters).`
  },
  {
    slug: 'too-good-to-ask-rule',
    title: 'The "Too Good to Ask" Rule',
    description: 'If any website/app asks for a permission it shouldn\'t need, deny it immediately.',
    category: 'Quick Tips',
    ...findImage('tip2'),
    content: `If any website/app asks for permission it shouldn't need: Deny it immediately. A flashlight app doesn't need your contacts. A calculator doesn't need your location. When in doubt, say no – the app will usually still work fine.`
  },
  {
    slug: 'restaurant-menu-password-method',
    title: 'The "Restaurant Menu" Password Method',
    description: 'Create passwords you can remember by thinking of your favorite restaurant\'s full menu name plus something personal.',
    category: 'Quick Tips',
    ...findImage('tip3'),
    content: `Create passwords you can remember: Think of your favorite restaurant's full menu name plus something personal. \`"Joe'sPizzaGarlicBread12!"\` is strong and you'll remember it because you love garlic bread. Add a number and symbol you'll remember.`
  },
  {
    slug: 'belt-and-suspenders-backup-rule',
    title: 'The "Belt and Suspenders" Backup Rule',
    description: 'Save important photos/documents in TWO places: a cloud service and a physical drive.',
    category: 'Quick Tips',
    ...findImage('tip4'),
    content: `Save important photos/documents in TWO places: Use Google Photos/Apple Photos AND copy them to a USB drive once a year. If one fails, you have the other. Label the drive "Family Photos 2024" not "Backup."`
  },
  {
    slug: 'public-wifi-test',
    title: 'The "Public Wi-Fi" Test',
    description: 'Before using public Wi-Fi for anything personal, ask yourself: "Would I write my password on a postcard and mail it?"',
    category: 'Quick Tips',
    ...findImage('tip5'),
    content: `Before using public Wi-Fi for anything personal: Ask yourself: "Would I write my password on a postcard and mail it?" If not, don't use public Wi-Fi for banking, email, or shopping. Save those for when you're on your home network.`
  },
  {
    slug: 'unexpected-package-response',
    title: 'The "Unexpected Package" Response',
    description: 'If you get a login alert you didn\'t trigger, don\'t click links in the alert. Go directly to the website yourself.',
    category: 'Quick Tips',
    ...findImage('tip6'),
    content: `If you get a login alert you didn't trigger (like "Someone logged into your account from Russia"): Don't click links in the alert email. Instead, go directly to the website yourself (type netflix.com, not click the link) and check your account or change your password.`
  },
  {
    slug: 'old-phone-cleanup',
    title: 'The "Old Phone" Cleanup',
    description: 'Before selling/giving away an old device, do a factory reset. Twice.',
    category: 'Quick Tips',
    ...findImage('tip7'),
    content: `Before selling/giving away an old phone/tablet: Do a factory reset (look it up for your device). Then, add a dummy account with fake info and do ANOTHER factory reset. This makes sure your personal stuff is really gone.`
  },
  {
    slug: 'payment-app-limit',
    title: 'The "Payment App" Limit',
    description: 'On Venmo/CashApp/PayPal, only keep "pocket money" in the balance, not your rent money.',
    category: 'Quick Tips',
    ...findImage('tip8'),
    content: `On Venmo/CashApp/PayPal: Only keep "pocket money" in the balance, not your rent money. Link it to a credit card instead of your main bank account if possible. Credit cards have better fraud protection if something goes wrong.`
  },
  {
    slug: 'qr-code-pause',
    title: 'The "QR Code" Pause',
    description: 'Before scanning any QR code in public, look at the URL preview that pops up. Does it look legit or weird?',
    category: 'Quick Tips',
    ...findImage('tip9'),
    content: `Before scanning any QR code in public (menus, posters, flyers): Look at the URL preview that pops up. Does it look legit or weird? If it's a restaurant menu, the URL should probably have the restaurant's name in it, not random letters.`
  },
  {
    slug: 'grandchild-scam-defense',
    title: 'The "Grandchild Scam" Defense',
    description: 'If anyone calls claiming to be a relative in trouble, hang up and call that person directly on the number you already have.',
    category: 'Quick Tips',
    ...findImage('tip10'),
    content: `If anyone calls claiming to be a relative in trouble (grandchild in jail, family member stranded): Hang up and call that person directly on the number you already have for them. If you can't reach them, call another family member to verify. Don't let them rush you.`
  },
  {
    slug: 'social-media-lockdown',
    title: 'The "Social Media Lockdown"',
    description: 'Spend 10 minutes today and set your social media privacy settings to "Friends Only" or "Only Me."',
    category: 'Quick Tips',
    ...findImage('tip11'),
    content: `Spend 10 minutes today: Go to Facebook/Instagram privacy settings → set everything to "Friends Only" or "Only Me." Future you will thank present you when that job interviewer can't see your vacation photos.`
  },
  {
    slug: 'credit-freeze-insurance',
    title: 'The "Credit Freeze" Insurance',
    description: 'Freeze your credit at all 3 bureaus (Equifax, Experian, TransUnion). It\'s free and prevents identity theft.',
    category: 'Quick Tips',
    ...findImage('tip12'),
    content: `Go to these 3 websites once: Equifax, Experian, TransUnion. Freeze your credit (it's free). When you need to apply for credit, you can temporarily unfreeze it. This prevents anyone from opening accounts in your name.`
  },
  {
    slug: 'recovery-contact-setup',
    title: 'The "Recovery Contact" Setup',
    description: 'Set up 2 trusted people as your account recovery contacts for Google/Apple to avoid getting locked out.',
    category: 'Quick Tips',
    ...findImage('tip13'),
    content: `Choose 2 people you trust: Set them as your account recovery contacts for Google/Apple. If you ever get locked out, they can help you get back in. Better they help you than you lose access forever.`
  },
  {
    slug: 'bank-alert-system',
    title: 'The "Bank Alert" System',
    description: 'Set up alerts in your banking app for large transactions or online purchases for peace of mind.',
    category: 'Quick Tips',
    ...findImage('tip14'),
    content: `Set up 2 alerts in your banking app: 1) Any transaction over $100, 2) Any online purchase. You'll get a text immediately if something happens. Peace of mind costs 2 minutes of setup.`
  },
  {
    slug: 'sharing-is-caring-exception',
    title: 'The "Sharing is Caring" Exception',
    description: 'Before posting photos online, ask yourself: "Would I be okay with this photo on a billboard?"',
    category: 'Quick Tips',
    ...findImage('tip15'),
    content: `Before posting photos online: Would you be okay with this photo on a billboard? If not, don't post it. Especially: photos of your home (shows valuables), kids' school names, anything with ID/credit cards in frame.`
  }
];
