// ============================================
// CyberWise Seed Lessons (Cybersecurity Basics)
// Beginner-friendly structured learning modules.
// ============================================

import type { Lesson, Quiz } from '@/types';

export const seedLessons: Lesson[] = [
  {
    id: 'lesson-what-is-cybersecurity',
    slug: 'what-is-cybersecurity',
    title: 'What is Cybersecurity?',
    description: 'Understand the basics of cybersecurity in simple, everyday language.',
    category: 'fundamentals',
    difficulty: 'beginner',
    estimatedMinutes: 8,
    xpReward: 30,
    skillIds: ['skill-fundamentals'],
    prerequisites: [],
    content: [
      {
        type: 'text',
        text: "Imagine your house. You lock the front door at night. You close the windows when you leave. Maybe you have a security camera or an alarm system. All of these are ways you protect your home, your family, and your stuff.",
      },
      {
        type: 'text',
        text: "Cybersecurity is exactly the same idea — but for your digital life. It's all the things you do to protect your computer, phone, accounts, and personal information from people who want to steal, damage, or misuse them.",
      },
      {
        type: 'heading',
        text: "Why Should You Care?",
        level: 2,
      },
      {
        type: 'text',
        text: "Every day, you use the internet for banking, shopping, messaging, emails, schoolwork, and social media. Each of these activities creates a digital trail — and criminals (just like in the physical world) look for easy opportunities.",
      },
      {
        type: 'list',
        items: [
          'A hacker might try to guess your password to get into your email.',
          'A scammer might send a fake message pretending to be your bank.',
          'Malware might sneak onto your computer through a bad download.',
          'Someone might steal your identity to open accounts in your name.',
        ],
      },
      {
        type: 'callout',
        variant: 'info',
        text: "You don't need to be a computer genius to be safe online. You just need to learn a few key habits and understand how the bad guys think.",
      },
      {
        type: 'heading',
        text: "The Three Core Goals of Cybersecurity",
        level: 2,
      },
      {
        type: 'text',
        text: "Security professionals call these the CIA Triad: Confidentiality, Integrity, and Availability. Sounds technical? Let's translate.",
      },
      {
        type: 'list',
        items: [
          "Confidentiality = Only the right people can see your stuff. (Like a diary with a lock.)",
          "Integrity = Your stuff hasn't been secretly changed. (Like a document that no one tampered with.)",
          "Availability = You can access your stuff when you need it. (Like your phone being unlocked and working when you need to call someone.)",
        ],
      },
      {
        type: 'text',
        text: "Almost everything in cybersecurity comes back to protecting these three things. A password protects confidentiality. A checksum protects integrity. A backup protects availability.",
      },
      {
        type: 'heading',
        text: "Who Are the Bad Guys?",
        level: 2,
      },
      {
        type: 'list',
        items: [
          'Scammers — want your money or personal info, often via phishing.',
          'Hackers — break into systems for money, fame, or ideology.',
          'Insiders — employees or people you know who misuse access.',
          'Nation-states — governments spying or attacking.',
        ],
      },
      {
        type: 'callout',
        variant: 'tip',
        text: "The good news: most attacks are NOT sophisticated. They rely on common mistakes — weak passwords, clicking bad links, ignoring updates. Learn to avoid those mistakes and you're already safer than 90% of users.",
      },
    ],
    quizId: 'quiz-what-is-cybersecurity',
    relatedChallengeIds: ['challenge-phishing-001'],
    relatedStoryIds: ['story-the-scholarship-email'],
    order: 1,
    published: true,
  },
  {
    id: 'lesson-password-security',
    slug: 'password-security',
    title: 'Password Security: Your First Line of Defense',
    description: 'Learn how to create strong passwords and why reusing them is so dangerous.',
    category: 'fundamentals',
    difficulty: 'beginner',
    estimatedMinutes: 10,
    xpReward: 35,
    skillIds: ['skill-fundamentals', 'skill-password-security'],
    prerequisites: ['lesson-what-is-cybersecurity'],
    content: [
      {
        type: 'text',
        text: "Your password is like the key to your digital front door. If someone gets your key, they can walk into your email, your bank, your social media — and everything connected to them.",
      },
      {
        type: 'heading',
        text: "What Makes a Password Strong?",
        level: 2,
      },
      {
        type: 'text',
        text: "A strong password is LONG. Length beats complexity every time. A 16-character password made of simple words is far stronger than an 8-character password made of random symbols.",
      },
      {
        type: 'text',
        text: "Why? Because hackers don't guess passwords — they run programs that try millions of combinations per second. Every extra character makes that job dramatically harder.",
      },
      {
        type: 'heading',
        text: "The Golden Rule: Never Reuse Passwords",
        level: 2,
      },
      {
        type: 'text',
        text: "This is the most important rule in password security. If a website you use gets hacked (it happens all the time), hackers get the password from that site. If you reused that same password on your bank, your email, and your social media — they now have access to everything.",
      },
      {
        type: 'callout',
        variant: 'warning',
        text: "Data breaches are normal now. Every month, millions of usernames and passwords leak online. The question isn't IF one of your accounts gets leaked — it's whether the leaked password opens anything else.",
      },
      {
        type: 'heading',
        text: "The Solution: A Password Manager",
        level: 2,
      },
      {
        type: 'list',
        items: [
          'A password manager stores all your passwords in one encrypted vault.',
          'You only need to remember ONE master password.',
          'It generates long, random, unique passwords for every site.',
          'It fills in your passwords for you, so you never need to type them.',
        ],
      },
      {
        type: 'text',
        text: "Popular options include Bitwarden (free and open-source), 1Password, and the built-in Google/Apple password managers.",
      },
      {
        type: 'heading',
        text: "Your Action Plan",
        level: 2,
      },
      {
        type: 'list',
        items: [
          "1. Set up a password manager this week.",
          "2. Change your most important passwords (email, bank, social) to unique random ones.",
          "3. Turn on Two-Factor Authentication (2FA) on your email at minimum.",
          "4. Never share passwords, even with 'tech support'.",
        ],
      },
    ],
    quizId: 'quiz-password-security',
    relatedChallengeIds: ['challenge-phishing-001'],
    order: 2,
    published: true,
  },
  {
    id: 'lesson-mfa',
    slug: 'two-factor-authentication',
    title: 'Two-Factor Authentication (2FA): The Second Lock',
    description: 'What is 2FA and why it is one of the most powerful protections you can enable.',
    category: 'fundamentals',
    difficulty: 'beginner',
    estimatedMinutes: 8,
    xpReward: 30,
    skillIds: ['skill-fundamentals', 'skill-password-security'],
    prerequisites: ['lesson-password-security'],
    content: [
      {
        type: 'text',
        text: "Imagine your front door has two locks. A thief needs two different keys to get in. That's the idea behind Two-Factor Authentication (2FA) — also called Multi-Factor Authentication (MFA).",
      },
      {
        type: 'heading',
        text: "How Does It Work?",
        level: 2,
      },
      {
        type: 'text',
        text: "When you log in, the service asks for your password AND a second piece of proof. The second factor is usually something you HAVE (like your phone), not something you KNOW (your password).",
      },
      {
        type: 'list',
        items: [
          'SMS code — sent to your phone by text message.',
          'Authenticator app — like Google Authenticator or Authy, generating codes offline.',
          'Physical security key — like a YubiKey you plug in or tap.',
          'Biometrics — your fingerprint or face.',
        ],
      },
      {
        type: 'heading',
        text: "Why Does It Matter?",
        level: 2,
      },
      {
        type: 'text',
        text: "Even if a hacker steals your password (through phishing or a data breach), they STILL can't get in without the second factor. That single step would have stopped the vast majority of real-world account takeovers.",
      },
      {
        type: 'callout',
        variant: 'info',
        text: "Authenticator apps and security keys are more secure than SMS codes, because text messages can be intercepted through SIM swapping. But ANY 2FA is far better than none.",
      },
      {
        type: 'heading',
        text: "Your Action Plan",
        level: 2,
      },
      {
        type: 'list',
        items: [
          "Turn on 2FA on your primary email FIRST — that's the key to everything else.",
          'Then enable it on your bank, social media, and any shopping accounts.',
          'Use an authenticator app whenever possible.',
          "Save your backup codes somewhere safe (offline).",
        ],
      },
    ],
    quizId: 'quiz-mfa',
    relatedChallengeIds: ['challenge-phishing-001'],
    order: 3,
    published: true,
  },
  {
    id: 'lesson-phishing',
    slug: 'phishing-basics',
    title: 'Phishing: The Most Common Attack',
    description: 'Learn how to spot phishing emails, texts, and messages — the #1 way people get hacked.',
    category: 'fundamentals',
    difficulty: 'beginner',
    estimatedMinutes: 10,
    xpReward: 40,
    skillIds: ['skill-fundamentals', 'skill-phishing-awareness', 'skill-email-security'],
    prerequisites: ['lesson-what-is-cybersecurity'],
    content: [
      {
        type: 'text',
        text: "Phishing (pronounced like 'fishing') is the most common cyberattack in the world. It works by sending a fake message — an email, text, or social media DM — that looks like it comes from a real company or person.",
      },
      {
        type: 'text',
        text: "The goal is simple: trick you into (1) clicking a malicious link, (2) downloading a malicious attachment, or (3) typing your password or credit card info into a fake website.",
      },
      {
        type: 'heading',
        text: "The Red Flags",
        level: 2,
      },
      {
        type: 'list',
        items: [
          "Sender address doesn't match the real domain (e.g., '@netflix-supports.com' instead of '@netflix.com').",
          'Urgency or threats — \u201cYour account will be suspended!\u201d \u201cAct immediately!\u201d',
          'Generic greetings — \u201cDear Customer\u201d instead of your name.',
          'Suspicious links — hover before you click to see the real URL.',
          'Grammar and spelling errors.',
          'Asking for personal information (a real company never emails you asking for your password).',
          'Unexpected attachments.',
        ],
      },
      {
        type: 'heading',
        text: "What Should You Do?",
        level: 2,
      },
      {
        type: 'list',
        items: [
          "Don't click suspicious links — navigate to the site directly by typing the address.",
          "Don't reply — even saying 'stop contacting me' confirms your email is active.",
          "Report it — forward to your IT team at work, or use the 'report spam' option in your email.",
          "If you already clicked or entered info: change the password immediately, enable 2FA, and check for unusual activity.",
        ],
      },
      {
        type: 'callout',
        variant: 'tip',
        text: "Remember: real companies NEVER ask for your password over email. If a message surprises you, assume it's fake until you verify through a separate channel.",
      },
    ],
    quizId: 'quiz-phishing',
    relatedChallengeIds: ['challenge-phishing-001', 'challenge-phishing-002', 'challenge-osint-001'],
    relatedStoryIds: ['story-the-scholarship-email'],
    order: 4,
    published: true,
  },
  {
    id: 'lesson-networks-101',
    slug: 'networks-101',
    title: 'Networks 101: How Computers Talk',
    description: 'Understand IP addresses, DNS, HTTP, and HTTPS — in plain language.',
    category: 'networking',
    difficulty: 'beginner',
    estimatedMinutes: 12,
    xpReward: 40,
    skillIds: ['skill-networking'],
    prerequisites: ['lesson-what-is-cybersecurity'],
    content: [
      {
        type: 'text',
        text: "Every time you visit a website, send an email, or stream a video, data travels across a network. Understanding a few basics of how this works makes cybersecurity much easier to understand.",
      },
      {
        type: 'heading',
        text: "IP Addresses: Digital Street Addresses",
        level: 2,
      },
      {
        type: 'text',
        text: "Every device on a network has an IP address — like a home address, but for computers. When one computer wants to send data to another, it uses the IP address to know where to send it.",
      },
      {
        type: 'text',
        text: "Example: 192.168.1.1 or 142.250.72.14. An IPv4 address has four parts separated by dots. (A newer standard, IPv6, looks like 2001:0db8:85a3:0000:0000:8a2e:0370:7334.)",
      },
      {
        type: 'heading',
        text: "DNS: The Internet's Phonebook",
        level: 2,
      },
      {
        type: 'text',
        text: "You don't type '142.250.72.14' into your browser — you type 'google.com'. The Domain Name System (DNS) translates human-friendly names into IP addresses. It's the internet's phonebook.",
      },
      {
        type: 'text',
        text: "Attackers love to abuse DNS. A fake website might use a slightly different name (like 'gooogle.com') or a different domain entirely. That's why checking the real domain matters so much.",
      },
      {
        type: 'heading',
        text: "HTTP vs HTTPS: The Secure vs Insecure Protocol",
        level: 2,
      },
      {
        type: 'text',
        text: "When your browser talks to a website, it uses a protocol called HTTP (HyperText Transfer Protocol). The 'S' in HTTPS stands for 'Secure' — it means the connection is encrypted so nobody in between can read the data.",
      },
      {
        type: 'callout',
        variant: 'warning',
        text: "Never type sensitive info (passwords, credit card numbers) into a site that doesn't have HTTPS. Look for the padlock icon in your browser's address bar. Note: attackers can also use HTTPS, so a padlock alone doesn't mean the site is legitimate.",
      },
      {
        type: 'heading',
        text: "What About Cookies and Sessions?",
        level: 2,
      },
      {
        type: 'text',
        text: "Cookies are small pieces of data a website stores in your browser, often to remember you. Sessions are the server-side record that you are logged in. Attackers steal tokens/cookies to impersonate you (session hijacking). Always log out on shared/public computers.",
      },
    ],
    quizId: 'quiz-networks',
    relatedChallengeIds: ['challenge-phishing-002'],
    order: 5,
    published: true,
  },
  {
    id: 'lesson-malware-ransomware',
    slug: 'malware-and-ransomware',
    title: 'Malware & Ransomware: The Digital Parasites',
    description: 'What viruses, trojans, and ransomware are, and how to defend against them.',
    category: 'defense',
    difficulty: 'beginner',
    estimatedMinutes: 10,
    xpReward: 35,
    skillIds: ['skill-fundamentals', 'skill-malware-analysis'],
    prerequisites: ['lesson-what-is-cybersecurity'],
    content: [
      {
        type: 'text',
        text: "Malware is short for 'malicious software' — any program designed to harm, exploit, or steal from you. You've probably heard names like viruses, trojans, and ransomware. Let's demystify them.",
      },
      {
        type: 'heading',
        text: "Viruses vs Trojans vs Worms",
        level: 2,
      },
      {
        type: 'list',
        items: [
          'Virus: Attaches to a file (like a document or program) and spreads when that file is opened.',
          "Trojan: Hides inside a seemingly legitimate program or file ('a gift horse'). You invite it in without knowing.",
          'Worm: Spreads across networks on its own, without needing a host file.',
          'Spyware: Secretly watches your activity and reports back to the attacker.',
          'Keylogger: Records every keystroke — a serious threat to passwords.',
          'Ransomware: Encrypts your files and demands payment to unlock them.',
        ],
      },
      {
        type: 'heading',
        text: "Ransomware: The Modern Plague",
        level: 2,
      },
      {
        type: 'text',
        text: "Ransomware is one of the most damaging threats today. You click a bad link or attachment, malware encrypts your photos, documents, and files, then a message appears: pay $500 in crypto or lose everything.",
      },
      {
        type: 'text',
        text: "The best defense? BACKUPS. If your files are safely backed up offline, ransomware loses its power — you can just restore and move on. Paying the ransom is NOT recommended (no guarantee you get files back, and it funds criminals).",
      },
      {
        type: 'heading',
        text: "How Malware Gets In",
        level: 2,
      },
      {
        type: 'list',
        items: [
          'Phishing emails with malicious attachments or links (the #1 vector).',
          'Fake downloads from shady websites or torrents.',
          'Exploiting unpatched software vulnerabilities.',
          'Malicious USB drives left in parking lots (yes, really).',
        ],
      },
      {
        type: 'heading',
        text: "Your Defenses",
        level: 2,
      },
      {
        type: 'list',
        items: [
          'Keep your OS and software updated (patches close the doors).',
          'Use reputable antivirus/EDR software and keep it updated.',
          'Never open unexpected attachments.',
          "Maintain the 3-2-1 backup rule: 3 copies, 2 different media, 1 off-site.",
          "Don't plug in unknown USB drives.",
        ],
      },
    ],
    quizId: 'quiz-malware',
    order: 6,
    published: true,
  },
  {
    id: 'lesson-iot-devices',
    slug: 'everyday-smart-devices',
    title: 'Everyday Smart Devices: Cameras, Routers, TVs',
    description: 'Routers, cameras, smart TVs, and meters are computers too — secure them like ones.',
    category: 'defense',
    difficulty: 'beginner',
    estimatedMinutes: 8,
    xpReward: 35,
    skillIds: ['skill-fundamentals'],
    prerequisites: ['lesson-what-is-cybersecurity'],
    content: [
      {
        type: 'text',
        text: "Your router, home camera, smart TV, and even electricity meter are small computers connected to the internet. Attackers love them because most people never change a single setting after plugging them in.",
      },
      {
        type: 'heading',
        text: "Change Default Passwords First",
        level: 2,
      },
      {
        type: 'text',
        text: "Cameras, routers, and baby monitors ship with passwords like 'admin/admin' printed in the manual — the same manual attackers can download. Changing the admin password (and the Wi-Fi password) on day one defeats mass automated break-ins.",
      },
      {
        type: 'heading',
        text: "Updates and Separate Networks",
        level: 2,
      },
      {
        type: 'list',
        items: [
          'Install firmware updates when the app or device offers them; unpatched devices stay hackable forever.',
          'Turn off features you do not use (remote access, cloud upload, voice control).',
          'If your router allows it, put smart devices on a separate guest Wi-Fi network from your phones and computers.',
          'Buy from brands that still release updates; abandoned devices become permanent risks.',
        ],
      },
      {
        type: 'heading',
        text: "Cameras, Microphones, and Kids",
        level: 2,
      },
      {
        type: 'text',
        text: "Think about who can see and hear through each camera and microphone: placement matters, shared accounts matter, and old devices you give away must be factory-reset first. For children, smart toys and connected devices can collect voice and location data — check privacy settings and parental controls together as a family.",
      },
      {
        type: 'callout',
        variant: 'tip',
        text: "The 5-minute rule: new device? Change the password, update it, turn off what you don't need. Done.",
      },
    ],
    quizId: 'quiz-iot',
    order: 7,
    published: true,
  },
];

export const seedQuizzes: Quiz[] = [
  {
    id: 'quiz-what-is-cybersecurity',
    lessonId: 'lesson-what-is-cybersecurity',
    title: 'What is Cybersecurity? Quiz',
    questions: [
      {
        id: 'q1',
        type: 'multiple-choice',
        question: 'The CIA Triad stands for...',
        options: ['Confidentiality, Integrity, Availability', 'Computer, Internet, Antivirus', 'Cryptography, Identity, Access', 'Coding, Integration, Automation'],
        correctAnswer: 'A',
        explanation: 'CIA stands for Confidentiality (only the right people see it), Integrity (nothing was changed), and Availability (you can access it when needed).',
        points: 20,
      },
      {
        id: 'q2',
        type: 'true-false',
        question: 'Most cyberattacks rely on simple human mistakes rather than sophisticated hacking.',
        options: ['True', 'False'],
        correctAnswer: 'True',
        explanation: 'Weak passwords, clicking bad links, and ignoring updates are the cause of most successful attacks.',
        points: 20,
      },
      {
        id: 'q3',
        type: 'scenario',
        question: "A scammer sends a message pretending to be your bank, asking you to 'verify' your account by clicking a link. Which part of the CIA Triad is being threatened?",
        options: ['Confidentiality (they want your password)', 'Integrity (they want to change your files)', 'Availability (they want to lock you out)', 'None of the above'],
        correctAnswer: 'A',
        explanation: 'By tricking you into entering your credentials on a fake site, the scammer is trying to break the confidentiality of your account.',
        points: 20,
      },
    ],
    passingScore: 60,
    xpReward: 30,
  },
  {
    id: 'quiz-password-security',
    lessonId: 'lesson-password-security',
    title: 'Password Security Quiz',
    questions: [
      {
        id: 'q1',
        type: 'multiple-choice',
        question: 'Which of these passwords is the strongest?',
        options: ['P@ssw0rd123', 'correct-horse-battery-staple', 'abc123', '12345678'],
        correctAnswer: 'B',
        explanation: 'Length beats complexity. A long passphrase like "correct-horse-battery-staple" is far stronger than a short password with symbols.',
        points: 20,
      },
      {
        id: 'q2',
        type: 'true-false',
        question: 'It is safe to reuse the same strong password on multiple sites if I change it every 6 months.',
        options: ['True', 'False'],
        correctAnswer: 'False',
        explanation: 'If any one site is breached, attackers will try that password on your other accounts. Unique passwords are required.',
        points: 20,
      },
      {
        id: 'q3',
        type: 'multiple-choice',
        question: 'What is the single best tool for managing unique passwords across all your accounts?',
        options: ['Writing them in a notebook', 'Using the same memorable password', 'A password manager', 'Storing them in a text file on your desktop'],
        correctAnswer: 'C',
        explanation: 'A password manager generates, stores, and fills unique passwords for each site so you only need to remember one master password.',
        points: 20,
      },
    ],
    passingScore: 60,
    xpReward: 35,
  },
  {
    id: 'quiz-mfa',
    lessonId: 'lesson-mfa',
    title: '2FA Quiz',
    questions: [
      {
        id: 'q1',
        type: 'multiple-choice',
        question: 'Two-Factor Authentication requires...',
        options: ['Two different passwords', 'Something you know (password) + something you have (phone/key)', 'Two emails to the same address', 'A second internet connection'],
        correctAnswer: 'B',
        explanation: '2FA combines a password with a second factor, usually something you physically have.',
        points: 20,
      },
      {
        id: 'q2',
        type: 'multiple-choice',
        question: 'Which 2FA method is generally the MOST secure?',
        options: ['SMS text codes', 'Email codes', 'Authenticator apps / hardware keys', 'Security questions'],
        correctAnswer: 'C',
        explanation: 'SMS can be intercepted via SIM swapping. Authenticator apps and hardware keys are offline and more secure.',
        points: 20,
      },
      {
        id: 'q3',
        type: 'scenario',
        question: "Your password was leaked in a data breach. Why would having 2FA enabled still protect you?",
        options: ['It would not help at all', "The attacker would also need your second factor to log in", '2FA changes your password automatically', 'The breach only applies to non-2FA accounts'],
        correctAnswer: 'B',
        explanation: 'Even with your password, the attacker cannot complete the login without your second factor (e.g., the code on your phone).',
        points: 20,
      },
    ],
    passingScore: 60,
    xpReward: 30,
  },
  {
    id: 'quiz-phishing',
    lessonId: 'lesson-phishing',
    title: 'Phishing Quiz',
    questions: [
      {
        id: 'q1',
        type: 'scenario',
        question: "You receive an email from 'support@tech-support-gadgets.net' claiming your Apple ID is locked and you must 'verify' within 24 hours. What is the strongest red flag?",
        options: ['The message creates urgency', 'The sender domain is not apple.com', 'It is written in English', 'It mentions Apple'],
        correctAnswer: 'B',
        explanation: 'The sender domain does not match Apple\'s real domain — this alone proves the message is not from Apple.',
        points: 20,
      },
      {
        id: 'q2',
        type: 'multiple-choice',
        question: 'What should you do if you receive a suspicious email from "your bank"?',
        options: [
          'Click the link to check if it is legitimate',
          'Reply asking if it is real',
          'Navigate to the bank website directly (type the address) or use the official app',
          'Forward it to friends to see what they think',
        ],
        correctAnswer: 'C',
        explanation: 'Always verify through a separate, trusted channel. Do not click links in the suspicious message.',
        points: 20,
      },
      {
        id: 'q3',
        type: 'identification',
        question: 'What does the expression "hover before you click" mean?',
        options: [
          'Move the cursor over a link to see the real destination URL before clicking',
          'Wait 30 seconds before clicking any link',
          'Only click links from websites you know',
          'Click with two fingers on a trackpad',
        ],
        correctAnswer: 'A',
        explanation: 'Hovering shows the true destination in your browser status bar, so you can spot deceptive links.',
        points: 20,
      },
    ],
    passingScore: 60,
    xpReward: 40,
  },
  {
    id: 'quiz-networks',
    lessonId: 'lesson-networks-101',
    title: 'Networks Quiz',
    questions: [
      {
        id: 'q1',
        type: 'multiple-choice',
        question: 'What does DNS do?',
        options: [
          'Encrypts all internet traffic',
          'Translates domain names (like google.com) into IP addresses',
          'Blocks malicious websites',
          'Stores your passwords',
        ],
        correctAnswer: 'B',
        explanation: 'DNS is the internet\'s phonebook — it maps human-readable names to machine addresses.',
        points: 20,
      },
      {
        id: 'q2',
        type: 'multiple-choice',
        question: 'What does the \u201cS\u201d in HTTPS stand for?',
        options: ['Server', 'Secure', 'Static', 'Shared'],
        correctAnswer: 'B',
        explanation: 'HTTPS means the connection is encrypted (secure). Look for the padlock icon.',
        points: 20,
      },
      {
        id: 'q3',
        type: 'true-false',
        question: 'A padlock icon in the browser means the website is always legitimate.',
        options: ['True', 'False'],
        correctAnswer: 'False',
        explanation: 'Attackers also use HTTPS. The padlock means the connection is encrypted, not that the site is honest.',
        points: 20,
      },
    ],
    passingScore: 60,
    xpReward: 40,
  },
  {
    id: 'quiz-malware',
    lessonId: 'lesson-malware-ransomware',
    title: 'Malware Quiz',
    questions: [
      {
        id: 'q1',
        type: 'multiple-choice',
        question: 'What is ransomware?',
        options: [
          'Software that steals your passwords',
          'Malware that encrypts your files and demands payment',
          'A type of antivirus',
          'Software that blocks ads',
        ],
        correctAnswer: 'B',
        explanation: 'Ransomware locks your files and demands a ransom to restore access.',
        points: 20,
      },
      {
        id: 'q2',
        type: 'multiple-choice',
        question: 'What is the single most effective defense against ransomware?',
        options: [
          'Paying the ransom quickly',
          'A strong firewall',
          'Regular offline backups',
          'An ad blocker',
        ],
        correctAnswer: 'C',
        explanation: 'If you have clean backups, ransomware loses its leverage — you can restore and move on.',
        points: 20,
      },
      {
        id: 'q3',
        type: 'multiple-choice',
        question: 'Which is the MOST common way malware ends up on a computer?',
        options: [
          'Phishing emails with malicious attachments or links',
          'Thermal temperature changes',
          'Old monitors',
          'Slow internet connections',
        ],
        correctAnswer: 'A',
        explanation: 'Phishing is the #1 infection vector for malware.',
        points: 20,
      },
    ],
    passingScore: 60,
    xpReward: 35,
  },
  {
    id: 'quiz-iot',
    lessonId: 'lesson-iot-devices',
    title: 'Smart Devices Quiz',
    questions: [
      {
        id: 'q1',
        type: 'multiple-choice',
        question: 'You just bought a home camera. What is the FIRST thing to do?',
        options: [
          'Plug it in facing the living room',
          'Change the default admin password',
          'Share access with the whole family',
          'Turn off automatic updates',
        ],
        correctAnswer: 'B',
        explanation: 'Default passwords like admin/admin are public knowledge. Changing them first defeats automated break-ins.',
        points: 20,
      },
      {
        id: 'q2',
        type: 'true-false',
        question: 'Putting smart devices on a separate guest Wi-Fi network improves safety.',
        options: ['True', 'False'],
        correctAnswer: 'True',
        explanation: 'Separation means a compromised camera cannot easily reach your phones and computers.',
        points: 20,
      },
      {
        id: 'q3',
        type: 'multiple-choice',
        question: 'Before giving away an old phone or camera, you should…',
        options: [
          'Just delete the photos you remember',
          'Factory-reset it and remove your accounts',
          'Leave it logged in for the next owner',
          'Throw it away with the passwords saved',
        ],
        correctAnswer: 'B',
        explanation: 'Only a factory reset plus account removal reliably wipes your data and access.',
        points: 20,
      },
    ],
    passingScore: 60,
    xpReward: 35,
  },
];